import {
  Icon3dCubeSphere,
  Icon3dRotate,
  IconAbacus,
  IconAccessPoint,
  IconAccessible,
  IconActivityHeartbeat,
  IconActivity,
  IconAd2,
  IconAd,
  IconAddressBook,
  IconAdjustments,
  IconAerialLift,
  IconAffiliate,
  IconAlarm,
  IconAlbum,
  IconAlertCircle,
  IconAlertOctagon,
  IconAlertTriangle,
  IconAlien,
  IconAlignLeft,
  IconAlphabetCyrillic,
  IconAlphabetGreek,
  IconAlphabetLatin,
  IconAmbulance,
  IconAmpersand,
  IconAnchor,
  IconAngle,
  IconAnkh,
  IconAntennaBars3,
  IconAntenna,
  IconAperture,
  IconApiApp,
  IconApi,
  IconAppWindow,
  IconApple,
  IconApps,
  IconArchive,
  IconArmchair2,
  IconArmchair,
  IconArrowsCross,
  IconArrowsDiagonal2,
  IconArrowsDiagonalMinimize2,
  IconArrowsDiagonalMinimize,
  IconArrowsDiagonal,
  IconArrowsDoubleNeSw,
  IconArrowsDoubleNwSe,
  IconArrowsDoubleSeNw,
  IconArrowsDoubleSwNe,
  IconArrowsDownUp,
  IconArrowsDown,
  IconArrowsExchange2,
  IconArrowsExchange,
  IconArrowsHorizontal,
  IconArrowsJoin2,
  IconArrowsJoin,
  IconArrowsLeftDown,
  IconArrowsLeftRight,
  IconArrowsLeft,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconArrowsMoveHorizontal,
  IconArrowsMoveVertical,
  IconArrowsMove,
  IconArrowsRandom,
  IconArrowsRightDown,
  IconArrowsRightLeft,
  IconArrowsRight,
  IconArrowsShuffle2,
  IconArrowsShuffle,
  IconArrowsSort,
  IconArrowsSplit2,
  IconArrowsSplit,
  IconArrowsUpDown,
  IconArrowsUpLeft,
  IconArrowsUpRight,
  IconArrowsUp,
  IconArrowsVertical,
  IconArtboard,
  IconArticle,
  IconAspectRatio,
  IconAssembly,
  IconAsset,
  IconAsteriskSimple,
  IconAsterisk,
  IconAt,
  IconAtom2,
  IconAtom,
  IconAugmentedReality,
  IconAward,
  IconAxe,
  IconAxisX,
  IconAxisY,
  IconBabyCarriage,
  IconBackhoe,
  IconBackpack,
  IconBackspace,
  IconBadge,
  IconBadges,
  IconBallAmericanFootball,
  IconBallBaseball,
  IconBallBasketball,
  IconBallBowling,
  IconBallFootball,
  IconBallTennis,
  IconBallVolleyball,
  IconBalloon,
  IconBallpen,
  IconBan,
  IconBandage,
  IconBarbell,
  IconBarcode,
  IconBarrel,
  IconBarrierBlock,
  IconBaseline,
  IconBasket,
  IconBat,
  IconBath,
  IconBattery4,
  IconBatteryAutomotive,
  IconBatteryCharging,
  IconBatteryEco,
  IconBattery,
  IconBeach,
  IconBed,
  IconBeer,
  IconBellMinus,
  IconBellPlus,
  IconBellRinging2,
  IconBellRinging,
  IconBellSchool,
  IconBellX,
  IconBellZ,
  IconBell,
  IconBible,
  IconBike,
  IconBinary,
  IconBiohazard,
  IconBlockquote,
  IconBluetoothConnected,
  IconBluetoothX,
  IconBluetooth,
  IconBlur,
  IconBold,
  IconBolt,
  IconBone,
  IconBook2,
  IconBookDownload,
  IconBookUpload,
  IconBook,
  IconBookmark,
  IconBookmarks,
  IconBooks,
  IconBorderTop,
  IconBorderVertical,
  IconBottle,
  IconBow,
  IconBoxMargin,
  IconBoxModel2,
  IconBoxModel,
  IconBoxMultiple,
  IconBoxPadding,
  IconBox,
  IconBraces,
  IconBracketsContainEnd,
  IconBracketsContainStart,
  IconBracketsContain,
  IconBrackets,
  IconBread,
  IconBriefcase,
  IconBrightness2,
  IconBrightnessDown,
  IconBrightnessHalf,
  IconBrightnessUp,
  IconBrightness,
  IconBroadcast,
  IconBrowserCheck,
  IconBrowserPlus,
  IconBrowserX,
  IconBrowser,
  IconBrush,
  IconBucket,
  IconBug,
  IconBuildingArch,
  IconBuildingBank,
  IconBuildingBridge2,
  IconBuildingBridge,
  IconBuildingCarousel,
  IconBuildingCastle,
  IconBuildingChurch,
  IconBuildingCommunity,
  IconBuildingCottage,
  IconBuildingFactory2,
  IconBuildingFactory,
  IconBuildingFortress,
  IconBuildingHospital,
  IconBuildingLighthouse,
  IconBuildingMonument,
  IconBuildingPavilion,
  IconBuildingSkyscraper,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconBuilding,
  IconBulb,
  IconBulldozer,
  IconBus,
  IconBusinessplan,
  IconButterfly,
  IconBrandCSharp,
  IconCactus,
  IconCake,
  IconCalculator,
  IconCalendarEvent,
  IconCalendarMinus,
  IconCalendarPlus,
  IconCalendarStats,
  IconCalendarTime,
  IconCalendar,
  IconCameraMinus,
  IconCameraPlus,
  IconCameraRotate,
  IconCameraSelfie,
  IconCamera,
  IconCandle,
  IconCandy,
  IconCapture,
  IconCarCrane,
  IconCarCrash,
  IconCar,
  IconCaravan,
  IconCardboards,
  IconCaretDown,
  IconCaretLeft,
  IconCaretRight,
  IconCaretUp,
  IconCarrot,
  IconCashBanknote,
  IconCash,
  IconCast,
  IconCategory2,
  IconCategory,
  IconCe,
  IconCellSignal1,
  IconCellSignal2,
  IconCellSignal3,
  IconCellSignal4,
  IconCellSignal5,
  IconCell,
  IconCertificate2,
  IconCertificate,
  IconChargingPile,
  IconChartArcs3,
  IconChartArcs,
  IconChartAreaLine,
  IconChartArea,
  IconChartArrowsVertical,
  IconChartArrows,
  IconChartBar,
  IconChartBubble,
  IconChartCandle,
  IconChartCircles,
  IconChartDonut2,
  IconChartDonut3,
  IconChartDonut4,
  IconChartDonut,
  IconChartDots2,
  IconChartDots3,
  IconChartDots,
  IconChartInfographic,
  IconChartLine,
  IconChartPie2,
  IconChartPie3,
  IconChartPie4,
  IconChartPie,
  IconChartRadar,
  IconCheck,
  IconCheckbox,
  IconChecklist,
  IconChecks,
  IconCheckupList,
  IconCheese,
  IconChefHat,
  IconChevronDownLeft,
  IconChevronDownRight,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUpLeft,
  IconChevronUpRight,
  IconChevronUp,
  IconChevronsDownLeft,
  IconChevronsDownRight,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconChevronsUpLeft,
  IconChevronsUpRight,
  IconChevronsUp,
  IconChristmasTree,
  IconCircleNumber0,
  IconCircleNumber1,
  IconCircleNumber2,
  IconCircleNumber3,
  IconCircleNumber4,
  IconCircleNumber5,
  IconCircleNumber6,
  IconCircleNumber7,
  IconCircleNumber8,
  IconCircleNumber9,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconCircleDotted,
  IconCircleHalf2,
  IconCircleHalfVertical,
  IconCircleHalf,
  IconCircleMinus,
  IconCirclePlus,
  IconCircleRectangle,
  IconCircleSquare,
  IconCircleTriangle,
  IconCircleX,
  IconCircle,
  IconCircles,
  IconCircuitAmmeter,
  IconCircuitBattery,
  IconCircuitBulb,
  IconCircuitCapacitorPolarized,
  IconCircuitCapacitor,
  IconCircuitCellPlus,
  IconCircuitCell,
  IconCircuitChangeover,
  IconCircuitDiodeZener,
  IconCircuitDiode,
  IconCircuitGroundDigital,
  IconCircuitGround,
  IconCircuitInductor,
  IconCircuitMotor,
  IconCircuitPushbutton,
  IconCircuitResistor,
  IconCircuitSwitchClosed,
  IconCircuitSwitchOpen,
  IconCircuitVoltmeter,
  IconClearAll,
  IconClearFormatting,
  IconClick,
  IconClipboardCheck,
  IconClipboardList,
  IconClipboardPlus,
  IconClipboardText,
  IconClipboardX,
  IconClipboard,
  IconClock2,
  IconClock,
  IconClothesRack,
  IconCloudComputing,
  IconCloudDataConnection,
  IconCloudDownload,
  IconCloudFog,
  IconCloudLockOpen,
  IconCloudLock,
  IconCloudRain,
  IconCloudSnow,
  IconCloudStorm,
  IconCloudUpload,
  IconCloud,
  IconClover2,
  IconClover,
  IconClubs,
  IconCodeMinus,
  IconCodePlus,
  IconCoin,
  IconColorPicker,
  IconColorSwatch,
  IconColumnInsertLeft,
  IconColumnInsertRight,
  IconColumns,
  IconComet,
  IconCommand,
  IconCompass,
  IconComponents,
  IconCone2,
  IconCone,
  IconConfetti,
  IconContainer,
  IconContrast2,
  IconContrast,
  IconCookie,
  IconCopy,
  IconCopyleft,
  IconCopyright,
  IconCornerDownLeftDouble,
  IconCornerDownLeft,
  IconCornerDownRightDouble,
  IconCornerDownRight,
  IconCornerLeftDownDouble,
  IconCornerLeftDown,
  IconCornerLeftUpDouble,
  IconCornerLeftUp,
  IconCornerRightDownDouble,
  IconCornerRightDown,
  IconCornerRightUpDouble,
  IconCornerRightUp,
  IconCornerUpLeftDouble,
  IconCornerUpLeft,
  IconCornerUpRightDouble,
  IconCornerUpRight,
  IconCpu2,
  IconCpu,
  IconCrane,
  IconCreativeCommonsBy,
  IconCreativeCommonsNc,
  IconCreativeCommonsNd,
  IconCreativeCommonsSa,
  IconCreativeCommonsZero,
  IconCreativeCommons,
  IconCreditCard,
  IconCricket,
  IconCrop,
  IconCross,
  IconCrosshair,
  IconCrown,
  IconCrutches,
  IconCup,
  IconCurling,
  IconCurlyLoop,
  IconCurrencyBahraini,
  IconCurrencyBaht,
  IconCurrencyBitcoin,
  IconCurrencyCent,
  IconCurrencyDinar,
  IconCurrencyDirham,
  IconCurrencyDogecoin,
  IconCurrencyDollarAustralian,
  IconCurrencyDollarCanadian,
  IconCurrencyDollarSingapore,
  IconCurrencyDollar,
  IconCurrencyEthereum,
  IconCurrencyEuro,
  IconCurrencyForint,
  IconCurrencyFrank,
  IconCurrencyKroneCzech,
  IconCurrencyKroneDanish,
  IconCurrencyKroneSwedish,
  IconCurrencyLeu,
  IconCurrencyLira,
  IconCurrencyLitecoin,
  IconCurrencyNaira,
  IconCurrencyPound,
  IconCurrencyReal,
  IconCurrencyRenminbi,
  IconCurrencyRipple,
  IconCurrencyRiyal,
  IconCurrencyRubel,
  IconCurrencyRupee,
  IconCurrencyShekel,
  IconCurrencyTaka,
  IconCurrencyTugrik,
  IconCurrencyWon,
  IconCurrencyYen,
  IconCurrencyZloty,
  IconCurrency,
  IconCurrentLocation,
  IconCursorText,
  IconCut,
  IconDashboard,
  IconDatabaseExport,
  IconDatabaseImport,
  IconDatabase,
  IconDentalBroken,
  IconDental,
  IconDetails,
  IconDeviceAnalytics,
  IconDeviceAudioTape,
  IconDeviceCameraPhone,
  IconDeviceCctv,
  IconDeviceComputerCamera,
  IconDeviceDesktopAnalytics,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceGamepad2,
  IconDeviceGamepad,
  IconDeviceHeartMonitor,
  IconDeviceLaptop,
  IconDeviceMobileCharging,
  IconDeviceMobileMessage,
  IconDeviceMobileRotated,
  IconDeviceMobileVibration,
  IconDeviceMobile,
  IconDeviceNintendo,
  IconDeviceSpeaker,
  IconDeviceTablet,
  IconDeviceTvOld,
  IconDeviceTv,
  IconDeviceWatchStats2,
  IconDeviceWatchStats,
  IconDeviceWatch,
  IconDevices2,
  IconDevicesPc,
  IconDevices,
  IconDialpad,
  IconDiamond,
  IconDiamonds,
  IconDice1,
  IconDice2,
  IconDice3,
  IconDice4,
  IconDice5,
  IconDice6,
  IconDice,
  IconDimensions,
  IconDirectionHorizontal,
  IconDirectionSign,
  IconDirection,
  IconDirections,
  IconDisabled2,
  IconDisabled,
  IconDisc,
  IconDiscount2,
  IconDiscountCheck,
  IconDiscount,
  IconDivide,
  IconDna2,
  IconDna,
  IconDogBowl,
  IconDoorEnter,
  IconDoorExit,
  IconDoor,
  IconDotsCircleHorizontal,
  IconDotsDiagonal2,
  IconDotsDiagonal,
  IconDotsVertical,
  IconDots,
  IconDownload,
  IconDragDrop2,
  IconDragDrop,
  IconDrone,
  IconDropCircle,
  IconDropletFilled,
  IconDropletHalf2,
  IconDropletHalf,
  IconDroplet,
  IconEar,
  IconEditCircle,
  IconEdit,
  IconEgg,
  IconElevator,
  IconEmergencyBed,
  IconEmphasis,
  IconEngine,
  IconEqualNot,
  IconEqual,
  IconEraser,
  IconError404,
  IconExchange,
  IconExclamationMark,
  IconExplicit,
  IconExposure,
  IconExternalLink,
  IconEyeCheck,
  IconEyeTable,
  IconEye,
  IconEyeglass2,
  IconEyeglass,
  IconFaceIdError,
  IconFaceId,
  IconFaceMask,
  IconFall,
  IconFeather,
  IconFence,
  IconFidgetSpinner,
  IconFile3d,
  IconFileAlert,
  IconFileAnalytics,
  IconFileArrowLeft,
  IconFileArrowRight,
  IconFileBarcode,
  IconFileCertificate,
  IconFileChart,
  IconFileCheck,
  IconFileCode2,
  IconFileCode,
  IconFileDatabase,
  IconFileDescription,
  IconFileDiff,
  IconFileDigit,
  IconFileDislike,
  IconFileDollar,
  IconFileDots,
  IconFileDownload,
  IconFileEuro,
  IconFileExport,
  IconFileHorizontal,
  IconFileImport,
  IconFileInfo,
  IconFileInvoice,
  IconFileLike,
  IconFileMinus,
  IconFileMusic,
  IconFilePencil,
  IconFilePhone,
  IconFilePlus,
  IconFilePower,
  IconFileReport,
  IconFileRss,
  IconFileScissors,
  IconFileSearch,
  IconFileSettings,
  IconFileShredder,
  IconFileSignal,
  IconFileSpreadsheet,
  IconFileStar,
  IconFileSymlink,
  IconFileText,
  IconFileTime,
  IconFileTypography,
  IconFileUnknown,
  IconFileUpload,
  IconFileVector,
  IconFileX,
  IconFileZip,
  IconFile,
  IconFiles,
  IconFilter,
  IconFingerprint,
  IconFiretruck,
  IconFirstAidKit,
  IconFishBone,
  IconFishHook,
  IconFish,
  IconFlag2,
  IconFlag3,
  IconFlag,
  IconFlame,
  IconFlare,
  IconFlask2,
  IconFlask,
  IconFlipHorizontal,
  IconFlipVertical,
  IconFloatCenter,
  IconFloatLeft,
  IconFloatNone,
  IconFloatRight,
  IconFlower,
  IconFocus2,
  IconFocusCentered,
  IconFocus,
  IconFoldDown,
  IconFoldUp,
  IconFold,
  IconFolderMinus,
  IconFolderPlus,
  IconFolderX,
  IconFolder,
  IconFolders,
  IconForbid2,
  IconForbid,
  IconForklift,
  IconForms,
  IconFountain,
  IconFrame,
  IconFreeRights,
  IconFridge,
  IconFriends,
  IconFunction,
  IconGardenCart,
  IconGasStation,
  IconGauge,
  IconGavel,
  IconGenderAgender,
  IconGenderAndrogyne,
  IconGenderBigender,
  IconGenderDemiboy,
  IconGenderDemigirl,
  IconGenderEpicene,
  IconGenderFemale,
  IconGenderFemme,
  IconGenderGenderfluid,
  IconGenderGenderless,
  IconGenderGenderqueer,
  IconGenderHermaphrodite,
  IconGenderIntergender,
  IconGenderMale,
  IconGenderNeutrois,
  IconGenderThird,
  IconGenderTransgender,
  IconGenderTrasvesti,
  IconGeometry,
  IconGhost,
  IconGif,
  IconGift,
  IconGitBranch,
  IconGitCommit,
  IconGitCompare,
  IconGitFork,
  IconGitMerge,
  IconGitPullRequestClosed,
  IconGitPullRequestDraft,
  IconGitPullRequest,
  IconGizmo,
  IconGlassFull,
  IconGlass,
  IconGlobe,
  IconGolf,
  IconGps,
  IconGrain,
  IconGraph,
  IconGridDots,
  IconGridPattern,
  IconGrill,
  IconGripHorizontal,
  IconGripVertical,
  IconGrowth,
  IconH1,
  IconH2,
  IconH3,
  IconH4,
  IconH5,
  IconH6,
  IconHammer,
  IconHandClick,
  IconHandFinger,
  IconHandGrab,
  IconHandLittleFinger,
  IconHandMiddleFinger,
  IconHandMove,
  IconHandRingFinger,
  IconHandRock,
  IconHandStop,
  IconHandThreeFingers,
  IconHandTwoFingers,
  IconHanger2,
  IconHanger,
  IconHash,
  IconHaze,
  IconHeading,
  IconHeadphones,
  IconHeadset,
  IconHealthRecognition,
  IconHeartBroken,
  IconHeartHandshake,
  IconHeartMinus,
  IconHeartPlus,
  IconHeartRateMonitor,
  IconHeart,
  IconHeartbeat,
  IconHelicopterLanding,
  IconHelicopter,
  IconHelmet,
  IconHelp,
  IconHexagon,
  IconHexagons,
  IconHierarchy2,
  IconHierarchy3,
  IconHierarchy,
  IconHighlight,
  IconHistoryToggle,
  IconHistory,
  IconHome2,
  IconHome,
  IconHorseToy,
  IconHotelService,
  IconHourglassEmpty,
  IconHourglassHigh,
  IconHourglassLow,
  IconHourglass,
  IconIceCream2,
  IconIceCream,
  IconIceSkating,
  IconIcons,
  IconIdBadge2,
  IconIdBadge,
  IconId,
  IconInbox,
  IconIndentDecrease,
  IconIndentIncrease,
  IconInfinity,
  IconInfoCircle,
  IconInfoSquare,
  IconItalic,
  IconJewishStar,
  IconJumpRope,
  IconKarate,
  IconKayak,
  IconKering,
  IconKey,
  IconKeyboardHide,
  IconKeyboardShow,
  IconKeyboard,
  IconLadder,
  IconLamp2,
  IconLamp,
  IconLanguageHiragana,
  IconLanguageKatakana,
  IconLanguage,
  IconLasso,
  IconLayersDifference,
  IconLayersIntersect2,
  IconLayersIntersect,
  IconLayersLinked,
  IconLayersSubtract,
  IconLayersUnion,
  IconLayout2,
  IconLayoutAlignBottom,
  IconLayoutAlignCenter,
  IconLayoutAlignLeft,
  IconLayoutAlignMiddle,
  IconLayoutAlignRight,
  IconLayoutAlignTop,
  IconLayoutBoardSplit,
  IconLayoutBoard,
  IconLayoutBottombarCollapse,
  IconLayoutBottombarExpand,
  IconLayoutBottombar,
  IconLayoutCards,
  IconLayoutColumns,
  IconLayoutDashboard,
  IconLayoutDistributeHorizontal,
  IconLayoutDistributeVertical,
  IconLayoutGridAdd,
  IconLayoutGrid,
  IconLayoutKanban,
  IconLayoutList,
  IconLayoutNavbarCollapse,
  IconLayoutNavbarExpand,
  IconLayoutNavbar,
  IconLayoutRows,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLayoutSidebarRightCollapse,
  IconLayoutSidebarRightExpand,
  IconLayoutSidebarRight,
  IconLayoutSidebar,
  IconLayout,
  IconLeaf,
  IconLego,
  IconLemon2,
  IconLemon,
  IconLetterA,
  IconLetterB,
  IconLetterC,
  IconLetterCaseLower,
  IconLetterCaseToggle,
  IconLetterCaseUpper,
  IconLetterCase,
  IconLetterD,
  IconLetterE,
  IconLetterF,
  IconLetterG,
  IconLetterH,
  IconLetterI,
  IconLetterJ,
  IconLetterK,
  IconLetterL,
  IconLetterM,
  IconLetterN,
  IconLetterO,
  IconLetterP,
  IconLetterQ,
  IconLetterR,
  IconLetterS,
  IconLetterSpacing,
  IconLetterT,
  IconLetterU,
  IconLetterV,
  IconLetterW,
  IconLetterX,
  IconLetterY,
  IconLetterZ,
  IconLicense,
  IconLifebuoy,
  IconLineDashed,
  IconLineDotted,
  IconLineHeight,
  IconLine,
  IconLink,
  IconListCheck,
  IconListDetails,
  IconListNumbers,
  IconListSearch,
  IconList,
  IconLivePhoto,
  IconLiveView,
  IconLoader2,
  IconLoaderQuarter,
  IconLoader,
  IconLocation,
  IconLockAccess,
  IconLockOpen,
  IconLockSquare,
  IconLock,
  IconLogicAnd,
  IconLogicBuffer,
  IconLogicNand,
  IconLogicNor,
  IconLogicNot,
  IconLogicOr,
  IconLogicXnor,
  IconLogicXor,
  IconLogin,
  IconLogout,
  IconLollipop,
  IconLuggage,
  IconLungs,
  IconMacro,
  IconMagnet,
  IconMailFast,
  IconMailForward,
  IconMailOpened,
  IconMail,
  IconMailbox,
  IconMan,
  IconManualGearbox,
  IconMap2,
  IconMapPin,
  IconMapPins,
  IconMapSearch,
  IconMap,
  IconMarkdown,
  IconMarquee2,
  IconMarquee,
  IconMars,
  IconMask,
  IconMasksTheater,
  IconMassage,
  IconMathAvg,
  IconMathFunction,
  IconMathMax,
  IconMathMin,
  IconMathSymbols,
  IconMath,
  IconMaximize,
  IconMeat,
  IconMedal2,
  IconMedal,
  IconMedicalCross,
  IconMedicineSyrup,
  IconMenu2,
  IconMenu,
  IconMessage2Code,
  IconMessage2Share,
  IconMessage2,
  IconMessageCircle2,
  IconMessageCircle,
  IconMessageCode,
  IconMessageDots,
  IconMessageForward,
  IconMessageLanguage,
  IconMessagePlus,
  IconMessageReport,
  IconMessageShare,
  IconMessage,
  IconMessages,
  IconMeteor,
  IconMicrophone2,
  IconMicrophone,
  IconMicroscope,
  IconMicrowave,
  IconMilitaryAward,
  IconMilitaryRank,
  IconMilk,
  IconMinimize,
  IconMinusVertical,
  IconMinus,
  IconMist,
  IconMoodBoy,
  IconMoodConfuzed,
  IconMoodCrazyHappy,
  IconMoodCry,
  IconMoodEmpty,
  IconMoodHappy,
  IconMoodKid,
  IconMoodNervous,
  IconMoodNeutral,
  IconMoodSad,
  IconMoodSmile,
  IconMoodSuprised,
  IconMoodTongue,
  IconMoon2,
  IconMoonStars,
  IconMoon,
  IconMoped,
  IconMotorbike,
  IconMountain,
  IconMouse2,
  IconMouse,
  IconMovie,
  IconMug,
  IconMultiplier05x,
  IconMultiplier15x,
  IconMultiplier1x,
  IconMultiplier2x,
  IconMushroom,
  IconMusic,
  IconNetwork,
  IconNewSection,
  IconNews,
  IconNfc,
  IconNoCopyright,
  IconNoCreativeCommons,
  IconNoDerivatives,
  IconNorthStar,
  IconNote,
  IconNotebook,
  IconNotes,
  IconNotification,
  IconNumber0,
  IconNumber1,
  IconNumber2,
  IconNumber3,
  IconNumber4,
  IconNumber5,
  IconNumber6,
  IconNumber7,
  IconNumber8,
  IconNumber9,
  IconNumber,
  IconNumbers,
  IconNurse,
  IconOctagon,
  IconOld,
  IconOlympics,
  IconOmega,
  IconOutbound,
  IconOutlet,
  IconOvalVertical,
  IconOval,
  IconOverline,
  IconPackage,
  IconPackageExport,
  IconPackageImport,
  IconPacman,
  IconPageBreak,
  IconPaint,
  IconPalette,
  IconPanoramaHorizontal,
  IconPanoramaVertical,
  IconPaperBag,
  IconPaperclip,
  IconParachute,
  IconParentheses,
  IconParking,
  IconPaw,
  IconPeace,
  IconPencilMinus,
  IconPencilPlus,
  IconPencil,
  IconPennant2,
  IconPennant,
  IconPentagon,
  IconPepper,
  IconPercentage,
  IconPerspective,
  IconPhoneCall,
  IconPhoneCalling,
  IconPhoneCheck,
  IconPhoneIncoming,
  IconPhoneOutgoing,
  IconPhonePause,
  IconPhonePlus,
  IconPhoneX,
  IconPhone,
  IconPhoto,
  IconPhysotherapist,
  IconPictureInPictureOn,
  IconPictureInPictureTop,
  IconPictureInPicture,
  IconPig,
  IconPill,
  IconPills,
  IconPin,
  IconPinned,
  IconPizza,
  IconPlaneArrival,
  IconPlaneDeparture,
  IconPlaneInflight,
  IconPlaneTilt,
  IconPlane,
  IconPlanet,
  IconPlant2,
  IconPlant,
  IconPlayCard,
  IconPlayerEject,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerRecord,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconPlaylistAdd,
  IconPlaylistX,
  IconPlaylist,
  IconPlugConnectedX,
  IconPlugConnected,
  IconPlugX,
  IconPlug,
  IconPlus,
  IconPodium,
  IconPoint,
  IconPointer,
  IconPokeball,
  IconPolaroid,
  IconPolygon,
  IconPoo,
  IconPool,
  IconPower,
  IconPray,
  IconPremiumRights,
  IconPrescription,
  IconPresentationAnalytics,
  IconPresentation,
  IconPrinter,
  IconPrison,
  IconPrompt,
  IconPropeller,
  IconPuzzle2,
  IconPuzzle,
  IconPyramid,
  IconQrcode,
  IconQuestionMark,
  IconQuote,
  IconRadar2,
  IconRadar,
  IconRadio,
  IconRadioactive,
  IconRadiusBottomLeft,
  IconRadiusBottomRight,
  IconRadiusTopLeft,
  IconRadiusTopRight,
  IconRainbow,
  IconRating12Plus,
  IconRating14Plus,
  IconRating16Plus,
  IconRating18Plus,
  IconRating21Plus,
  IconReceipt2,
  IconReceiptRefund,
  IconReceiptTax,
  IconReceipt,
  IconRecharging,
  IconRecordMail,
  IconRectangleVertical,
  IconRectangle,
  IconRecycle,
  IconRefreshAlert,
  IconRefreshDot,
  IconRefresh,
  IconRegistered,
  IconRelationManyToMany,
  IconRelationOneToMany,
  IconRelationOneToOne,
  IconRepeatOnce,
  IconRepeat,
  IconReplace,
  IconReportAnalytics,
  IconReportMedical,
  IconReportMoney,
  IconReportSearch,
  IconReport,
  IconResize,
  IconRipple,
  IconRoadSign,
  IconRoad,
  IconRobot,
  IconRocket,
  IconRollerSkating,
  IconRollercoaster,
  IconRotate2,
  IconRotate360,
  IconRotateClockwise2,
  IconRotateClockwise,
  IconRotateDot,
  IconRotateRectangle,
  IconRotate,
  IconRoute,
  IconRouter,
  IconRowInsertBottom,
  IconRowInsertTop,
  IconRss,
  IconRuler2,
  IconRuler3,
  IconRulerMeasure,
  IconRuler,
  IconRun,
  IconSailboat,
  IconSalt,
  IconSatellite,
  IconSausage,
  IconScaleOutline,
  IconScale,
  IconScanEye,
  IconScan,
  IconSchema,
  IconSchool,
  IconScissors,
  IconScooterElectric,
  IconScooter,
  IconScreenShare,
  IconScreenshot,
  IconScribble,
  IconScubaMask,
  IconSearch,
  IconSectionSign,
  IconSection,
  IconSeeding,
  IconSelect,
  IconSelector,
  IconSend,
  IconSeo,
  IconSeparatorHorizontal,
  IconSeparatorVertical,
  IconSeparator,
  IconServer2,
  IconServer,
  IconServicemark,
  IconSettingsAutomation,
  IconSettings,
  IconShadow,
  IconShape2,
  IconShape3,
  IconShape,
  IconShare,
  IconShieldCheck,
  IconShieldCheckered,
  IconShieldChevron,
  IconShieldLock,
  IconShieldX,
  IconShield,
  IconShip,
  IconShirtSport,
  IconShirt,
  IconShoe,
  IconShoppingCartDiscount,
  IconShoppingCartPlus,
  IconShoppingCartX,
  IconShoppingCart,
  IconShovel,
  IconShredder,
  IconSignLeft,
  IconSignRight,
  IconSignal3g,
  IconSignal4gPlus,
  IconSignal4g,
  IconSignal5g,
  IconSignature,
  IconSitemap,
  IconSkateboard,
  IconSkull,
  IconSleigh,
  IconSlice,
  IconSlideshow,
  IconSmartHome,
  IconSmokingNo,
  IconSmoking,
  IconSnowflake,
  IconSnowman,
  IconSoccerField,
  IconSocial,
  IconSock,
  IconSofa,
  IconSortAscending2,
  IconSortAscendingLetters,
  IconSortAscendingNumbers,
  IconSortAscending,
  IconSortDescending2,
  IconSortDescendingLetters,
  IconSortDescendingNumbers,
  IconSortDescending,
  IconSos,
  IconSoup,
  IconSpace,
  IconSpacingHorizontal,
  IconSpacingVertical,
  IconSpade,
  IconSpeakerphone,
  IconSpeedboat,
  IconSpider,
  IconSpiral,
  IconSportBillard,
  IconSpy,
  IconSquareF0,
  IconSquareF1,
  IconSquareF2,
  IconSquareF3,
  IconSquareF4,
  IconSquareF5,
  IconSquareF6,
  IconSquareF7,
  IconSquareF8,
  IconSquareF9,
  IconSquareAsterisk,
  IconSquareCheck,
  IconSquareDot,
  IconSquareForbid2,
  IconSquareForbid,
  IconSquareHalf,
  IconSquareMinus,
  IconSquarePlus,
  IconSquareRoot2,
  IconSquareRoot,
  IconSquareRotatedForbid2,
  IconSquareRotatedForbid,
  IconSquareRotated,
  IconSquareToggleHorizontal,
  IconSquareToggle,
  IconSquareX,
  IconSquare,
  IconSquaresDiagonal,
  IconSquaresFilled,
  IconStack2,
  IconStack3,
  IconStackPop,
  IconStackPush,
  IconStack,
  IconStairsDown,
  IconStairsUp,
  IconStairs,
  IconStarHalf,
  IconStar,
  IconStars,
  IconSteam,
  IconSteeringWheel,
  IconStepInto,
  IconStepOut,
  IconStethoscope,
  IconSticker,
  IconStorm,
  IconStrikethrough,
  IconSubmarine,
  IconSubscript,
  IconSubtask,
  IconSum,
  IconSunHigh,
  IconSunLow,
  IconSunWind,
  IconSun,
  IconSunglasses,
  IconSunrise,
  IconSunset2,
  IconSunset,
  IconSuperscript,
  IconSvg,
  IconSwimming,
  IconSwitch2,
  IconSwitch3,
  IconSwitchHorizontal,
  IconSwitchVertical,
  IconSwitch,
  IconSword,
  IconSwords,
  IconTableAlias,
  IconTableExport,
  IconTableImport,
  IconTableOptions,
  IconTableShortcut,
  IconTable,
  IconTag,
  IconTags,
  IconTallymark1,
  IconTallymark2,
  IconTallymark3,
  IconTallymark4,
  IconTallymarks,
  IconTank,
  IconTarget,
  IconTelescope,
  IconTemperatureCelsius,
  IconTemperatureFahrenheit,
  IconTemperatureMinus,
  IconTemperaturePlus,
  IconTemperature,
  IconTemplate,
  IconTent,
  IconTerminal2,
  IconTerminal,
  IconTestPipe2,
  IconTestPipe,
  IconTextDecrease,
  IconTextDirectionLtr,
  IconTextDirectionRtl,
  IconTextIncrease,
  IconTextRecognition,
  IconTextResize,
  IconTextWrapDisabled,
  IconTextWrap,
  IconThermometer,
  IconThumbDown,
  IconThumbUp,
  IconTicket,
  IconTie,
  IconTiltShift,
  IconTimeline,
  IconTir,
  IconToggleLeft,
  IconToggleRight,
  IconToiletPaper,
  IconTool,
  IconToolsKitchen2,
  IconToolsKitchen,
  IconTools,
  IconTornado,
  IconTournament,
  IconTrack,
  IconTractor,
  IconTrademark,
  IconTrafficCone,
  IconTrafficLights,
  IconTrain,
  IconTransferIn,
  IconTransferOut,
  IconTrashX,
  IconTrash,
  IconTree,
  IconTrees,
  IconTrendingDown2,
  IconTrendingDown3,
  IconTrendingDown,
  IconTrendingUp2,
  IconTrendingUp3,
  IconTrendingUp,
  IconTriangleInverted,
  IconTriangleSquareCircle,
  IconTriangle,
  IconTriangles,
  IconTrident,
  IconTrophy,
  IconTruckDelivery,
  IconTruckLoading,
  IconTruckReturn,
  IconTruck,
  IconTypography,
  IconUfo,
  IconUmbrella,
  IconUnderline,
  IconUnlink,
  IconUpload,
  IconUrgent,
  IconUsb,
  IconUserCheck,
  IconUserCircle,
  IconUserExclamation,
  IconUserMinus,
  IconUserPlus,
  IconUserSearch,
  IconUserX,
  IconUser,
  IconUsers,
  IconVaccineBottle,
  IconVaccine,
  IconVariable,
  IconVectorBezier2,
  IconVectorBezier,
  IconVectorTriangle,
  IconVector,
  IconVenus,
  IconVersions,
  IconVideoMinus,
  IconVideoPlus,
  IconVideo,
  IconView360,
  IconViewfinder,
  IconViewportNarrow,
  IconViewportWide,
  IconVinyl,
  IconVirusSearch,
  IconVirus,
  IconVocabulary,
  IconVolume2,
  IconVolume3,
  IconVolume,
  IconWalk,
  IconWall,
  IconWallet,
  IconWallpaper,
  IconWand,
  IconWashMachine,
  IconWaveSawTool,
  IconWaveSine,
  IconWaveSquare,
  IconWebhook,
  IconWheelchair,
  IconWifi0,
  IconWifi1,
  IconWifi2,
  IconWifi,
  IconWind,
  IconWindmill,
  IconWindowMaximize,
  IconWindowMinimize,
  IconWindow,
  IconWindsock,
  IconWiperWash,
  IconWiper,
  IconWoman,
  IconWorldDownload,
  IconWorldLatitude,
  IconWorldLongitude,
  IconWorldUpload,
  IconWorld,
  IconWreckingBall,
  IconWritingSign,
  IconWriting,
  IconX,
  IconYinYang,
  IconYoga,
  IconZeppelin,
  IconZodiacAquarius,
  IconZodiacAries,
  IconZodiacCancer,
  IconZodiacCapricorn,
  IconZodiacGemini,
  IconZodiacLeo,
  IconZodiacLibra,
  IconZodiacPisces,
  IconZodiacSagittarius,
  IconZodiacScorpio,
  IconZodiacTaurus,
  IconZodiacVirgo,
  IconZoomCancel,
  IconZoomCheck,
  IconZoomCode,
  IconZoomExclamation,
  IconZoomInArea,
  IconZoomIn,
  IconZoomMoney,
  IconZoomOutArea,
  IconZoomOut,
  IconZoomPan,
  IconZoomQuestion,
  IconZoomReset,
  IconZzz,
  IconCode,
  TablerIconsProps
} from "@tabler/icons-solidjs"
import { Component } from "solid-js"

export const namedIcons: { [key: string]: Component<TablerIconsProps> | undefined } = {
  "3dCubeSphere": Icon3dCubeSphere,
  "3dRotate": Icon3dRotate,
  Abacus: IconAbacus,
  AccessPoint: IconAccessPoint,
  Accessible: IconAccessible,
  ActivityHeartbeat: IconActivityHeartbeat,
  Activity: IconActivity,
  Ad2: IconAd2,
  Ad: IconAd,
  AddressBook: IconAddressBook,
  Adjustments: IconAdjustments,
  AerialLift: IconAerialLift,
  Affiliate: IconAffiliate,
  Alarm: IconAlarm,
  Album: IconAlbum,
  AlertCircle: IconAlertCircle,
  AlertOctagon: IconAlertOctagon,
  AlertTriangle: IconAlertTriangle,
  Alien: IconAlien,
  AlignLeft: IconAlignLeft,
  AlphabetCyrillic: IconAlphabetCyrillic,
  AlphabetGreek: IconAlphabetGreek,
  AlphabetLatin: IconAlphabetLatin,
  Ambulance: IconAmbulance,
  Ampersand: IconAmpersand,
  Anchor: IconAnchor,
  Angle: IconAngle,
  Ankh: IconAnkh,
  AntennaBars3: IconAntennaBars3,
  Antenna: IconAntenna,
  Aperture: IconAperture,
  ApiApp: IconApiApp,
  Api: IconApi,
  AppWindow: IconAppWindow,
  Apple: IconApple,
  Apps: IconApps,
  Archive: IconArchive,
  Armchair2: IconArmchair2,
  Armchair: IconArmchair,
  ArrowsCross: IconArrowsCross,
  ArrowsDiagonal2: IconArrowsDiagonal2,
  ArrowsDiagonalMinimize2: IconArrowsDiagonalMinimize2,
  ArrowsDiagonalMinimize: IconArrowsDiagonalMinimize,
  ArrowsDiagonal: IconArrowsDiagonal,
  ArrowsDoubleNeSw: IconArrowsDoubleNeSw,
  ArrowsDoubleNwSe: IconArrowsDoubleNwSe,
  ArrowsDoubleSeNw: IconArrowsDoubleSeNw,
  ArrowsDoubleSwNe: IconArrowsDoubleSwNe,
  ArrowsDownUp: IconArrowsDownUp,
  ArrowsDown: IconArrowsDown,
  ArrowsExchange2: IconArrowsExchange2,
  ArrowsExchange: IconArrowsExchange,
  ArrowsHorizontal: IconArrowsHorizontal,
  ArrowsJoin2: IconArrowsJoin2,
  ArrowsJoin: IconArrowsJoin,
  ArrowsLeftDown: IconArrowsLeftDown,
  ArrowsLeftRight: IconArrowsLeftRight,
  ArrowsLeft: IconArrowsLeft,
  ArrowsMaximize: IconArrowsMaximize,
  ArrowsMinimize: IconArrowsMinimize,
  ArrowsMoveHorizontal: IconArrowsMoveHorizontal,
  ArrowsMoveVertical: IconArrowsMoveVertical,
  ArrowsMove: IconArrowsMove,
  ArrowsRandom: IconArrowsRandom,
  ArrowsRightDown: IconArrowsRightDown,
  ArrowsRightLeft: IconArrowsRightLeft,
  ArrowsRight: IconArrowsRight,
  ArrowsShuffle2: IconArrowsShuffle2,
  ArrowsShuffle: IconArrowsShuffle,
  ArrowsSort: IconArrowsSort,
  ArrowsSplit2: IconArrowsSplit2,
  ArrowsSplit: IconArrowsSplit,
  ArrowsUpDown: IconArrowsUpDown,
  ArrowsUpLeft: IconArrowsUpLeft,
  ArrowsUpRight: IconArrowsUpRight,
  ArrowsUp: IconArrowsUp,
  ArrowsVertical: IconArrowsVertical,
  Artboard: IconArtboard,
  Article: IconArticle,
  AspectRatio: IconAspectRatio,
  Assembly: IconAssembly,
  Asset: IconAsset,
  AsteriskSimple: IconAsteriskSimple,
  Asterisk: IconAsterisk,
  At: IconAt,
  Atom2: IconAtom2,
  Atom: IconAtom,
  AugmentedReality: IconAugmentedReality,
  Award: IconAward,
  Axe: IconAxe,
  AxisX: IconAxisX,
  AxisY: IconAxisY,
  BabyCarriage: IconBabyCarriage,
  Backhoe: IconBackhoe,
  Backpack: IconBackpack,
  Backspace: IconBackspace,
  Badge: IconBadge,
  Badges: IconBadges,
  BallAmericanFootball: IconBallAmericanFootball,
  BallBaseball: IconBallBaseball,
  BallBasketball: IconBallBasketball,
  BallBowling: IconBallBowling,
  BallFootball: IconBallFootball,
  BallTennis: IconBallTennis,
  BallVolleyball: IconBallVolleyball,
  Ballon: IconBalloon,
  Ballpen: IconBallpen,
  Ban: IconBan,
  Bandage: IconBandage,
  Barbell: IconBarbell,
  Barcode: IconBarcode,
  Barrel: IconBarrel,
  BarrierBlock: IconBarrierBlock,
  Baseline: IconBaseline,
  Basket: IconBasket,
  Bat: IconBat,
  Bath: IconBath,
  Battery4: IconBattery4,
  BatteryAutomotive: IconBatteryAutomotive,
  BatteryCharging: IconBatteryCharging,
  BatteryEco: IconBatteryEco,
  Battery: IconBattery,
  Beach: IconBeach,
  Bed: IconBed,
  Beer: IconBeer,
  BellMinus: IconBellMinus,
  BellPlus: IconBellPlus,
  BellRinging2: IconBellRinging2,
  BellRinging: IconBellRinging,
  BellSchool: IconBellSchool,
  BellX: IconBellX,
  BellZ: IconBellZ,
  Bell: IconBell,
  Bible: IconBible,
  Bike: IconBike,
  Binary: IconBinary,
  Biohazard: IconBiohazard,
  Blockquote: IconBlockquote,
  BluetoothConnected: IconBluetoothConnected,
  BluetoothX: IconBluetoothX,
  Bluetooth: IconBluetooth,
  Blur: IconBlur,
  Bold: IconBold,
  Bolt: IconBolt,
  Bone: IconBone,
  Book2: IconBook2,
  BookDownload: IconBookDownload,
  BookUpload: IconBookUpload,
  Book: IconBook,
  Bookmark: IconBookmark,
  Bookmarks: IconBookmarks,
  Books: IconBooks,
  BorderTop: IconBorderTop,
  BorderVertical: IconBorderVertical,
  Bottle: IconBottle,
  Bow: IconBow,
  BoxMargin: IconBoxMargin,
  BoxModel2: IconBoxModel2,
  BoxModel: IconBoxModel,
  BoxMultiple: IconBoxMultiple,
  BoxPadding: IconBoxPadding,
  Box: IconBox,
  Braces: IconBraces,
  BracketsContainEnd: IconBracketsContainEnd,
  BracketsContainStart: IconBracketsContainStart,
  BracketsContain: IconBracketsContain,
  Brackets: IconBrackets,
  Bread: IconBread,
  Briefcase: IconBriefcase,
  Brightness2: IconBrightness2,
  BrightnessDown: IconBrightnessDown,
  BrightnessHalf: IconBrightnessHalf,
  BrightnessUp: IconBrightnessUp,
  Brightness: IconBrightness,
  Broadcast: IconBroadcast,
  BrowserCheck: IconBrowserCheck,
  BrowserPlus: IconBrowserPlus,
  BrowserX: IconBrowserX,
  Browser: IconBrowser,
  Brush: IconBrush,
  Bucket: IconBucket,
  Bug: IconBug,
  BuildingArch: IconBuildingArch,
  BuildingBank: IconBuildingBank,
  BuildingBridge2: IconBuildingBridge2,
  BuildingBridge: IconBuildingBridge,
  BuildingCarousel: IconBuildingCarousel,
  BuildingCastle: IconBuildingCastle,
  BuildingChurch: IconBuildingChurch,
  BuildingCommunity: IconBuildingCommunity,
  BuildingCottage: IconBuildingCottage,
  BuildingFactory2: IconBuildingFactory2,
  BuildingFactory: IconBuildingFactory,
  BuildingFortress: IconBuildingFortress,
  BuildingHospital: IconBuildingHospital,
  BuildingLighthouse: IconBuildingLighthouse,
  BuildingMonument: IconBuildingMonument,
  BuildingPavilon: IconBuildingPavilion,
  BuildingSkyscraper: IconBuildingSkyscraper,
  BuildingStore: IconBuildingStore,
  BuildingWarehouse: IconBuildingWarehouse,
  Building: IconBuilding,
  Bulb: IconBulb,
  Bulldozer: IconBulldozer,
  Bus: IconBus,
  Businessplan: IconBusinessplan,
  Butterfly: IconButterfly,
  CSharp: IconBrandCSharp,
  Cactus: IconCactus,
  Cake: IconCake,
  Calculator: IconCalculator,
  CalendarEvent: IconCalendarEvent,
  CalendarMinus: IconCalendarMinus,
  CalendarPlus: IconCalendarPlus,
  CalendarStats: IconCalendarStats,
  CalendarTime: IconCalendarTime,
  Calendar: IconCalendar,
  CameraMinus: IconCameraMinus,
  CameraPlus: IconCameraPlus,
  CameraRotate: IconCameraRotate,
  CameraSelfie: IconCameraSelfie,
  Camera: IconCamera,
  Candle: IconCandle,
  Candy: IconCandy,
  Capture: IconCapture,
  CarCrane: IconCarCrane,
  CarCrash: IconCarCrash,
  Car: IconCar,
  Caravan: IconCaravan,
  Cardboards: IconCardboards,
  CaretDown: IconCaretDown,
  CaretLeft: IconCaretLeft,
  CaretRight: IconCaretRight,
  CaretUp: IconCaretUp,
  Carrot: IconCarrot,
  CashBanknote: IconCashBanknote,
  Cash: IconCash,
  Cast: IconCast,
  Category2: IconCategory2,
  Category: IconCategory,
  Ce: IconCe,
  CellSignal1: IconCellSignal1,
  CellSignal2: IconCellSignal2,
  CellSignal3: IconCellSignal3,
  CellSignal4: IconCellSignal4,
  CellSignal5: IconCellSignal5,
  Cell: IconCell,
  Certificate2: IconCertificate2,
  Certificate: IconCertificate,
  ChargingPile: IconChargingPile,
  ChartArcs3: IconChartArcs3,
  ChartArcs: IconChartArcs,
  ChartAreaLine: IconChartAreaLine,
  ChartArea: IconChartArea,
  ChartArrowsVertical: IconChartArrowsVertical,
  ChartArrows: IconChartArrows,
  ChartBar: IconChartBar,
  ChartBubble: IconChartBubble,
  ChartCandle: IconChartCandle,
  ChartCircles: IconChartCircles,
  ChartDonut2: IconChartDonut2,
  ChartDonut3: IconChartDonut3,
  ChartDonut4: IconChartDonut4,
  ChartDonut: IconChartDonut,
  ChartDots2: IconChartDots2,
  ChartDots3: IconChartDots3,
  ChartDots: IconChartDots,
  ChartInfographic: IconChartInfographic,
  ChartLine: IconChartLine,
  ChartPie2: IconChartPie2,
  ChartPie3: IconChartPie3,
  ChartPie4: IconChartPie4,
  ChartPie: IconChartPie,
  ChartRadar: IconChartRadar,
  Check: IconCheck,
  Checkbox: IconCheckbox,
  Checklist: IconChecklist,
  Checks: IconChecks,
  CheckupList: IconCheckupList,
  Cheese: IconCheese,
  ChefHat: IconChefHat,
  ChevronDownLeft: IconChevronDownLeft,
  ChevronDownRight: IconChevronDownRight,
  ChevronDown: IconChevronDown,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronUpLeft: IconChevronUpLeft,
  ChevronUpRight: IconChevronUpRight,
  ChevronUp: IconChevronUp,
  ChevronsDownLeft: IconChevronsDownLeft,
  ChevronsDownRight: IconChevronsDownRight,
  ChevronsDown: IconChevronsDown,
  ChevronsLeft: IconChevronsLeft,
  ChevronsRight: IconChevronsRight,
  ChevronsUpLeft: IconChevronsUpLeft,
  ChevronsUpRight: IconChevronsUpRight,
  ChevronsUp: IconChevronsUp,
  ChristmasTree: IconChristmasTree,
  Circle0: IconCircleNumber0,
  Circle1: IconCircleNumber1,
  Circle2: IconCircleNumber2,
  Circle3: IconCircleNumber3,
  Circle4: IconCircleNumber4,
  Circle5: IconCircleNumber5,
  Circle6: IconCircleNumber6,
  Circle7: IconCircleNumber7,
  Circle8: IconCircleNumber8,
  Circle9: IconCircleNumber9,
  CircleCheck: IconCircleCheck,
  CircleDashed: IconCircleDashed,
  CircleDot: IconCircleDot,
  CircleDotted: IconCircleDotted,
  CircleHalf2: IconCircleHalf2,
  CircleHalfVertical: IconCircleHalfVertical,
  CircleHalf: IconCircleHalf,
  CircleMinus: IconCircleMinus,
  CirclePlus: IconCirclePlus,
  CircleRectangle: IconCircleRectangle,
  CircleSquare: IconCircleSquare,
  CircleTriangle: IconCircleTriangle,
  CircleX: IconCircleX,
  Circle: IconCircle,
  Circles: IconCircles,
  CircuitAmmeter: IconCircuitAmmeter,
  CircuitBattery: IconCircuitBattery,
  CircuitBulb: IconCircuitBulb,
  CircuitCapacitorPolarized: IconCircuitCapacitorPolarized,
  CircuitCapacitor: IconCircuitCapacitor,
  CircuitCellPlus: IconCircuitCellPlus,
  CircuitCell: IconCircuitCell,
  CircuitChangeover: IconCircuitChangeover,
  CircuitDiodeZener: IconCircuitDiodeZener,
  CircuitDiode: IconCircuitDiode,
  CircuitGroundDigital: IconCircuitGroundDigital,
  CircuitGround: IconCircuitGround,
  CircuitInductor: IconCircuitInductor,
  CircuitMotor: IconCircuitMotor,
  CircuitPushbutton: IconCircuitPushbutton,
  CircuitResistor: IconCircuitResistor,
  CircuitSwitchClosed: IconCircuitSwitchClosed,
  CircuitSwitchOpen: IconCircuitSwitchOpen,
  CircuitVoltmeter: IconCircuitVoltmeter,
  ClearAll: IconClearAll,
  ClearFormatting: IconClearFormatting,
  Click: IconClick,
  ClipboardCheck: IconClipboardCheck,
  ClipboardList: IconClipboardList,
  ClipboardPlus: IconClipboardPlus,
  ClipboardText: IconClipboardText,
  ClipboardX: IconClipboardX,
  Clipboard: IconClipboard,
  Clock2: IconClock2,
  Clock: IconClock,
  ClothesRack: IconClothesRack,
  CloudComputing: IconCloudComputing,
  CloudDataConnection: IconCloudDataConnection,
  CloudDownload: IconCloudDownload,
  CloudFog: IconCloudFog,
  CloudLockOpen: IconCloudLockOpen,
  CloudLock: IconCloudLock,
  CloudRain: IconCloudRain,
  CloudSnow: IconCloudSnow,
  CloudStorm: IconCloudStorm,
  CloudUpload: IconCloudUpload,
  Cloud: IconCloud,
  Clover2: IconClover2,
  Clover: IconClover,
  Clubs: IconClubs,
  CodeMinus: IconCodeMinus,
  CodePlus: IconCodePlus,
  Code: IconCode,
  Coin: IconCoin,
  ColorPicker: IconColorPicker,
  ColorSwatch: IconColorSwatch,
  ColumnInsertLeft: IconColumnInsertLeft,
  ColumnInsertRight: IconColumnInsertRight,
  Columns: IconColumns,
  Comet: IconComet,
  Command: IconCommand,
  Compass: IconCompass,
  Components: IconComponents,
  Cone2: IconCone2,
  Cone: IconCone,
  Confetti: IconConfetti,
  Container: IconContainer,
  Contrast2: IconContrast2,
  Contrast: IconContrast,
  Cookie: IconCookie,
  Copy: IconCopy,
  Copyleft: IconCopyleft,
  Copyright: IconCopyright,
  CornerDownLeftDouble: IconCornerDownLeftDouble,
  CornerDownLeft: IconCornerDownLeft,
  CornerDownRightDouble: IconCornerDownRightDouble,
  CornerDownRight: IconCornerDownRight,
  CornerLeftDownDouble: IconCornerLeftDownDouble,
  CornerLeftDown: IconCornerLeftDown,
  CornerLeftUpDouble: IconCornerLeftUpDouble,
  CornerLeftUp: IconCornerLeftUp,
  CornerRightDownDouble: IconCornerRightDownDouble,
  CornerRightDown: IconCornerRightDown,
  CornerRightUpDouble: IconCornerRightUpDouble,
  CornerRightUp: IconCornerRightUp,
  CornerUpLeftDouble: IconCornerUpLeftDouble,
  CornerUpLeft: IconCornerUpLeft,
  CornerUpRightDouble: IconCornerUpRightDouble,
  CornerUpRight: IconCornerUpRight,
  Cpu2: IconCpu2,
  Cpu: IconCpu,
  Crane: IconCrane,
  CreativeCommonsBy: IconCreativeCommonsBy,
  CreativeCommonsNc: IconCreativeCommonsNc,
  CreativeCommonsNd: IconCreativeCommonsNd,
  CreativeCommonsSa: IconCreativeCommonsSa,
  CreativeCommonsZero: IconCreativeCommonsZero,
  CreativeCommons: IconCreativeCommons,
  CreditCard: IconCreditCard,
  Cricket: IconCricket,
  Crop: IconCrop,
  Cross: IconCross,
  Crosshair: IconCrosshair,
  Crown: IconCrown,
  Crutches: IconCrutches,
  Cup: IconCup,
  Curling: IconCurling,
  CurlyLoop: IconCurlyLoop,
  CurrencyBahraini: IconCurrencyBahraini,
  CurrencyBaht: IconCurrencyBaht,
  CurrencyBitcoin: IconCurrencyBitcoin,
  CurrencyCent: IconCurrencyCent,
  CurrencyDinar: IconCurrencyDinar,
  CurrencyDirham: IconCurrencyDirham,
  CurrencyDogecoin: IconCurrencyDogecoin,
  CurrencyDollarAustralian: IconCurrencyDollarAustralian,
  CurrencyDollarCanadian: IconCurrencyDollarCanadian,
  CurrencyDollarSingapore: IconCurrencyDollarSingapore,
  CurrencyDollar: IconCurrencyDollar,
  CurrencyEthereum: IconCurrencyEthereum,
  CurrencyEuro: IconCurrencyEuro,
  CurrencyForint: IconCurrencyForint,
  CurrencyFrank: IconCurrencyFrank,
  CurrencyKroneCzech: IconCurrencyKroneCzech,
  CurrencyKroneDanish: IconCurrencyKroneDanish,
  CurrencyKroneSwedish: IconCurrencyKroneSwedish,
  CurrencyLeu: IconCurrencyLeu,
  CurrencyLira: IconCurrencyLira,
  CurrencyLitecoin: IconCurrencyLitecoin,
  CurrencyNaira: IconCurrencyNaira,
  CurrencyPound: IconCurrencyPound,
  CurrencyReal: IconCurrencyReal,
  CurrencyRenminbi: IconCurrencyRenminbi,
  CurrencyRipple: IconCurrencyRipple,
  CurrencyRiyal: IconCurrencyRiyal,
  CurrencyRubel: IconCurrencyRubel,
  CurrencyRupee: IconCurrencyRupee,
  CurrencyShekel: IconCurrencyShekel,
  CurrencyTaka: IconCurrencyTaka,
  CurrencyTugrik: IconCurrencyTugrik,
  CurrencyWon: IconCurrencyWon,
  CurrencyYen: IconCurrencyYen,
  CurrencyZloty: IconCurrencyZloty,
  Currency: IconCurrency,
  CurrentLocation: IconCurrentLocation,
  CursorText: IconCursorText,
  Cut: IconCut,
  Dashboard: IconDashboard,
  DatabaseExport: IconDatabaseExport,
  DatabaseImport: IconDatabaseImport,
  Database: IconDatabase,
  DentalBroken: IconDentalBroken,
  Dental: IconDental,
  Details: IconDetails,
  DeviceAnalytics: IconDeviceAnalytics,
  DeviceAudioTape: IconDeviceAudioTape,
  DeviceCameraPhone: IconDeviceCameraPhone,
  DeviceCctv: IconDeviceCctv,
  DeviceComputerCamera: IconDeviceComputerCamera,
  DeviceDesktopAnalytics: IconDeviceDesktopAnalytics,
  DeviceDesktop: IconDeviceDesktop,
  DeviceFloppy: IconDeviceFloppy,
  DeviceGamepad2: IconDeviceGamepad2,
  DeviceGamepad: IconDeviceGamepad,
  DeviceHeartMonitor: IconDeviceHeartMonitor,
  DeviceLaptop: IconDeviceLaptop,
  DeviceMobileCharging: IconDeviceMobileCharging,
  DeviceMobileMessage: IconDeviceMobileMessage,
  DeviceMobileRotated: IconDeviceMobileRotated,
  DeviceMobileVibration: IconDeviceMobileVibration,
  DeviceMobile: IconDeviceMobile,
  DeviceNintendo: IconDeviceNintendo,
  DeviceSpeaker: IconDeviceSpeaker,
  DeviceTablet: IconDeviceTablet,
  DeviceTvOld: IconDeviceTvOld,
  DeviceTv: IconDeviceTv,
  DeviceWatchStats2: IconDeviceWatchStats2,
  DeviceWatchStats: IconDeviceWatchStats,
  DeviceWatch: IconDeviceWatch,
  Devices2: IconDevices2,
  DevicesPc: IconDevicesPc,
  Devices: IconDevices,
  Dialpad: IconDialpad,
  Diamond: IconDiamond,
  Diamonds: IconDiamonds,
  Dice1: IconDice1,
  Dice2: IconDice2,
  Dice3: IconDice3,
  Dice4: IconDice4,
  Dice5: IconDice5,
  Dice6: IconDice6,
  Dice: IconDice,
  Dimensions: IconDimensions,
  DirectionHorizontal: IconDirectionHorizontal,
  DirectionSign: IconDirectionSign,
  Direction: IconDirection,
  Directions: IconDirections,
  Disabled2: IconDisabled2,
  Disabled: IconDisabled,
  Disc: IconDisc,
  Discount2: IconDiscount2,
  DiscountCheck: IconDiscountCheck,
  Discount: IconDiscount,
  Divide: IconDivide,
  Dna2: IconDna2,
  Dna: IconDna,
  DogBowl: IconDogBowl,
  DoorEnter: IconDoorEnter,
  DoorExit: IconDoorExit,
  Door: IconDoor,
  DotsCircleHorizontal: IconDotsCircleHorizontal,
  DotsDiagonal2: IconDotsDiagonal2,
  DotsDiagonal: IconDotsDiagonal,
  DotsVertical: IconDotsVertical,
  Dots: IconDots,
  Download: IconDownload,
  DragDrop2: IconDragDrop2,
  DragDrop: IconDragDrop,
  Drone: IconDrone,
  DropCircle: IconDropCircle,
  DropletFilled: IconDropletFilled,
  DropletHalf2: IconDropletHalf2,
  DropletHalf: IconDropletHalf,
  Droplet: IconDroplet,
  Ear: IconEar,
  EditCircle: IconEditCircle,
  Edit: IconEdit,
  Egg: IconEgg,
  Elevator: IconElevator,
  EmergencyBed: IconEmergencyBed,
  Emphasis: IconEmphasis,
  Engine: IconEngine,
  EqualNot: IconEqualNot,
  Equal: IconEqual,
  Eraser: IconEraser,
  Error404: IconError404,
  Exchange: IconExchange,
  ExclamationMark: IconExclamationMark,
  Explicit: IconExplicit,
  Exposure: IconExposure,
  ExternalLink: IconExternalLink,
  EyeCheck: IconEyeCheck,
  EyeTable: IconEyeTable,
  Eye: IconEye,
  Eyeglass2: IconEyeglass2,
  Eyeglass: IconEyeglass,
  FaceIdError: IconFaceIdError,
  FaceId: IconFaceId,
  FaceMask: IconFaceMask,
  Fall: IconFall,
  Feather: IconFeather,
  Fence: IconFence,
  FidgetSpinner: IconFidgetSpinner,
  File3d: IconFile3d,
  FileAlert: IconFileAlert,
  FileAnalytics: IconFileAnalytics,
  FileArrowLeft: IconFileArrowLeft,
  FileArrowRight: IconFileArrowRight,
  FileBarcode: IconFileBarcode,
  FileCertificate: IconFileCertificate,
  FileChart: IconFileChart,
  FileCheck: IconFileCheck,
  FileCode2: IconFileCode2,
  FileCode: IconFileCode,
  FileDatabase: IconFileDatabase,
  FileDescription: IconFileDescription,
  FileDiff: IconFileDiff,
  FileDigit: IconFileDigit,
  FileDislike: IconFileDislike,
  FileDollar: IconFileDollar,
  FileDots: IconFileDots,
  FileDownload: IconFileDownload,
  FileEuro: IconFileEuro,
  FileExport: IconFileExport,
  FileHorizontal: IconFileHorizontal,
  FileImport: IconFileImport,
  FileInfo: IconFileInfo,
  FileInvoice: IconFileInvoice,
  FileLike: IconFileLike,
  FileMinus: IconFileMinus,
  FileMusic: IconFileMusic,
  FilePencil: IconFilePencil,
  FilePhone: IconFilePhone,
  FilePlus: IconFilePlus,
  FilePower: IconFilePower,
  FileReport: IconFileReport,
  FileRss: IconFileRss,
  FileScissors: IconFileScissors,
  FileSearch: IconFileSearch,
  FileSettings: IconFileSettings,
  FileShredder: IconFileShredder,
  FileSignal: IconFileSignal,
  FileSpreadsheet: IconFileSpreadsheet,
  FileStar: IconFileStar,
  FileSymlink: IconFileSymlink,
  FileText: IconFileText,
  FileTime: IconFileTime,
  FileTypography: IconFileTypography,
  FileUnknown: IconFileUnknown,
  FileUpload: IconFileUpload,
  FileVector: IconFileVector,
  FileX: IconFileX,
  FileZip: IconFileZip,
  File: IconFile,
  Files: IconFiles,
  Filter: IconFilter,
  Fingerprint: IconFingerprint,
  Firetruck: IconFiretruck,
  FirstAidKit: IconFirstAidKit,
  FishBone: IconFishBone,
  FishHook: IconFishHook,
  Fish: IconFish,
  Flag2: IconFlag2,
  Flag3: IconFlag3,
  Flag: IconFlag,
  Flame: IconFlame,
  Flare: IconFlare,
  Flask2: IconFlask2,
  Flask: IconFlask,
  FlipHorizontal: IconFlipHorizontal,
  FlipVertical: IconFlipVertical,
  FloatCenter: IconFloatCenter,
  FloatLeft: IconFloatLeft,
  FloatNone: IconFloatNone,
  FloatRight: IconFloatRight,
  Flower: IconFlower,
  Focus2: IconFocus2,
  FocusCentered: IconFocusCentered,
  Focus: IconFocus,
  FoldDown: IconFoldDown,
  FoldUp: IconFoldUp,
  Fold: IconFold,
  FolderMinus: IconFolderMinus,
  FolderPlus: IconFolderPlus,
  FolderX: IconFolderX,
  Folder: IconFolder,
  Folders: IconFolders,
  Forbid2: IconForbid2,
  Forbid: IconForbid,
  Forklift: IconForklift,
  Forms: IconForms,
  Fountain: IconFountain,
  Frame: IconFrame,
  FreeRights: IconFreeRights,
  Fridge: IconFridge,
  Friends: IconFriends,
  Function: IconFunction,
  GardenCart: IconGardenCart,
  GasStation: IconGasStation,
  Gauge: IconGauge,
  Gavel: IconGavel,
  GenderAgender: IconGenderAgender,
  GenderAndrogyne: IconGenderAndrogyne,
  GenderBigender: IconGenderBigender,
  GenderDemiboy: IconGenderDemiboy,
  GenderDemigirl: IconGenderDemigirl,
  GenderEpicene: IconGenderEpicene,
  GenderFemale: IconGenderFemale,
  GenderFemme: IconGenderFemme,
  GenderGenderfluid: IconGenderGenderfluid,
  GenderGenderless: IconGenderGenderless,
  GenderGenderqueer: IconGenderGenderqueer,
  GenderHermaphrodite: IconGenderHermaphrodite,
  GenderIntergender: IconGenderIntergender,
  GenderMale: IconGenderMale,
  GenderNeutrois: IconGenderNeutrois,
  GenderThird: IconGenderThird,
  GenderTransgender: IconGenderTransgender,
  GenderTrasvesti: IconGenderTrasvesti,
  Geometry: IconGeometry,
  Ghost: IconGhost,
  Gif: IconGif,
  Gift: IconGift,
  GitBranch: IconGitBranch,
  GitCommit: IconGitCommit,
  GitCompare: IconGitCompare,
  GitFork: IconGitFork,
  GitMerge: IconGitMerge,
  GitPullRequestClosed: IconGitPullRequestClosed,
  GitPullRequestDraft: IconGitPullRequestDraft,
  GitPullRequest: IconGitPullRequest,
  Gizmo: IconGizmo,
  GlassFull: IconGlassFull,
  Glass: IconGlass,
  Globe: IconGlobe,
  Golf: IconGolf,
  Gps: IconGps,
  Grain: IconGrain,
  Graph: IconGraph,
  GridDots: IconGridDots,
  GridPattern: IconGridPattern,
  Grill: IconGrill,
  GripHorizontal: IconGripHorizontal,
  GripVertical: IconGripVertical,
  Growth: IconGrowth,
  H1: IconH1,
  H2: IconH2,
  H3: IconH3,
  H4: IconH4,
  H5: IconH5,
  H6: IconH6,
  Hammer: IconHammer,
  HandClick: IconHandClick,
  HandFinger: IconHandFinger,
  HandGrab: IconHandGrab,
  HandLittleFinger: IconHandLittleFinger,
  HandMiddleFinger: IconHandMiddleFinger,
  HandMove: IconHandMove,
  HandRingFinger: IconHandRingFinger,
  HandRock: IconHandRock,
  HandStop: IconHandStop,
  HandThreeFingers: IconHandThreeFingers,
  HandTwoFingers: IconHandTwoFingers,
  Hanger2: IconHanger2,
  Hanger: IconHanger,
  Hash: IconHash,
  Haze: IconHaze,
  Heading: IconHeading,
  Headphones: IconHeadphones,
  Headset: IconHeadset,
  HealthRecognition: IconHealthRecognition,
  HeartBroken: IconHeartBroken,
  HeartHandshake: IconHeartHandshake,
  HeartMinus: IconHeartMinus,
  HeartPlus: IconHeartPlus,
  HeartRateMonitor: IconHeartRateMonitor,
  Heart: IconHeart,
  Heartbeat: IconHeartbeat,
  HelicopterLanding: IconHelicopterLanding,
  Helicopter: IconHelicopter,
  Helmet: IconHelmet,
  Help: IconHelp,
  Hexagon: IconHexagon,
  Hexagons: IconHexagons,
  Hierarchy2: IconHierarchy2,
  Hierarchy3: IconHierarchy3,
  Hierarchy: IconHierarchy,
  Highlight: IconHighlight,
  HistoryToggle: IconHistoryToggle,
  History: IconHistory,
  Home2: IconHome2,
  Home: IconHome,
  HorseToy: IconHorseToy,
  HotelService: IconHotelService,
  HourglassEmpty: IconHourglassEmpty,
  HourglassHigh: IconHourglassHigh,
  HourglassLow: IconHourglassLow,
  Hourglass: IconHourglass,
  IceCream2: IconIceCream2,
  IceCream: IconIceCream,
  IceSkating: IconIceSkating,
  Icons: IconIcons,
  IdBadge2: IconIdBadge2,
  IdBadge: IconIdBadge,
  Id: IconId,
  Inbox: IconInbox,
  IndentDecrease: IconIndentDecrease,
  IndentIncrease: IconIndentIncrease,
  Infinity: IconInfinity,
  InfoCircle: IconInfoCircle,
  InfoSquare: IconInfoSquare,
  Italic: IconItalic,
  JewishStar: IconJewishStar,
  JumpRope: IconJumpRope,
  Karate: IconKarate,
  Kayak: IconKayak,
  Kering: IconKering,
  Key: IconKey,
  KeyboardHide: IconKeyboardHide,
  KeyboardShow: IconKeyboardShow,
  Keyboard: IconKeyboard,
  Ladder: IconLadder,
  Lamp2: IconLamp2,
  Lamp: IconLamp,
  LanguageHiragana: IconLanguageHiragana,
  LanguageKatakana: IconLanguageKatakana,
  Language: IconLanguage,
  Lasso: IconLasso,
  LayersDifference: IconLayersDifference,
  LayersIntersect2: IconLayersIntersect2,
  LayersIntersect: IconLayersIntersect,
  LayersLinked: IconLayersLinked,
  LayersSubtract: IconLayersSubtract,
  LayersUnion: IconLayersUnion,
  Layout2: IconLayout2,
  LayoutAlignBottom: IconLayoutAlignBottom,
  LayoutAlignCenter: IconLayoutAlignCenter,
  LayoutAlignLeft: IconLayoutAlignLeft,
  LayoutAlignMiddle: IconLayoutAlignMiddle,
  LayoutAlignRight: IconLayoutAlignRight,
  LayoutAlignTop: IconLayoutAlignTop,
  LayoutBoardSplit: IconLayoutBoardSplit,
  LayoutBoard: IconLayoutBoard,
  LayoutBottombarCollapse: IconLayoutBottombarCollapse,
  LayoutBottombarExpand: IconLayoutBottombarExpand,
  LayoutBottombar: IconLayoutBottombar,
  LayoutCards: IconLayoutCards,
  LayoutColumns: IconLayoutColumns,
  LayoutDashboard: IconLayoutDashboard,
  LayoutDistributeHorizontal: IconLayoutDistributeHorizontal,
  LayoutDistributeVertical: IconLayoutDistributeVertical,
  LayoutGridAdd: IconLayoutGridAdd,
  LayoutGrid: IconLayoutGrid,
  LayoutKanban: IconLayoutKanban,
  LayoutList: IconLayoutList,
  LayoutNavbarCollapse: IconLayoutNavbarCollapse,
  LayoutNavbarExpand: IconLayoutNavbarExpand,
  LayoutNavbar: IconLayoutNavbar,
  LayoutRows: IconLayoutRows,
  LayoutSidebarLeftCollapse: IconLayoutSidebarLeftCollapse,
  LayoutSidebarLeftExpand: IconLayoutSidebarLeftExpand,
  LayoutSidebarRightCollapse: IconLayoutSidebarRightCollapse,
  LayoutSidebarRightExpand: IconLayoutSidebarRightExpand,
  LayoutSidebarRight: IconLayoutSidebarRight,
  LayoutSidebar: IconLayoutSidebar,
  Layout: IconLayout,
  Leaf: IconLeaf,
  Lego: IconLego,
  Lemon2: IconLemon2,
  Lemon: IconLemon,
  LetterA: IconLetterA,
  LetterB: IconLetterB,
  LetterC: IconLetterC,
  LetterCaseLower: IconLetterCaseLower,
  LetterCaseToggle: IconLetterCaseToggle,
  LetterCaseUpper: IconLetterCaseUpper,
  LetterCase: IconLetterCase,
  LetterD: IconLetterD,
  LetterE: IconLetterE,
  LetterF: IconLetterF,
  LetterG: IconLetterG,
  LetterH: IconLetterH,
  LetterI: IconLetterI,
  LetterJ: IconLetterJ,
  LetterK: IconLetterK,
  LetterL: IconLetterL,
  LetterM: IconLetterM,
  LetterN: IconLetterN,
  LetterO: IconLetterO,
  LetterP: IconLetterP,
  LetterQ: IconLetterQ,
  LetterR: IconLetterR,
  LetterS: IconLetterS,
  LetterSpacing: IconLetterSpacing,
  LetterT: IconLetterT,
  LetterU: IconLetterU,
  LetterV: IconLetterV,
  LetterW: IconLetterW,
  LetterX: IconLetterX,
  LetterY: IconLetterY,
  LetterZ: IconLetterZ,
  License: IconLicense,
  Lifebuoy: IconLifebuoy,
  LineDashed: IconLineDashed,
  LineDotted: IconLineDotted,
  LineHeight: IconLineHeight,
  Line: IconLine,
  Link: IconLink,
  ListCheck: IconListCheck,
  ListDetails: IconListDetails,
  ListNumbers: IconListNumbers,
  ListSearch: IconListSearch,
  List: IconList,
  LivePhoto: IconLivePhoto,
  LiveView: IconLiveView,
  Loader2: IconLoader2,
  LoaderQuarter: IconLoaderQuarter,
  Loader: IconLoader,
  Location: IconLocation,
  LockAccess: IconLockAccess,
  LockOpen: IconLockOpen,
  LockSquare: IconLockSquare,
  Lock: IconLock,
  LogicAnd: IconLogicAnd,
  LogicBuffer: IconLogicBuffer,
  LogicNand: IconLogicNand,
  LogicNor: IconLogicNor,
  LogicNot: IconLogicNot,
  LogicOr: IconLogicOr,
  LogicXnor: IconLogicXnor,
  LogicXor: IconLogicXor,
  Login: IconLogin,
  Logout: IconLogout,
  Lollipop: IconLollipop,
  Luggage: IconLuggage,
  Lungs: IconLungs,
  Macro: IconMacro,
  Magnet: IconMagnet,
  MailFast: IconMailFast,
  MailForward: IconMailForward,
  MailOpened: IconMailOpened,
  Mail: IconMail,
  Mailbox: IconMailbox,
  Man: IconMan,
  ManualGearbox: IconManualGearbox,
  Map2: IconMap2,
  MapPin: IconMapPin,
  MapPins: IconMapPins,
  MapSearch: IconMapSearch,
  Map: IconMap,
  Markdown: IconMarkdown,
  Marquee2: IconMarquee2,
  Marquee: IconMarquee,
  Mars: IconMars,
  Mask: IconMask,
  MasksTheater: IconMasksTheater,
  Massage: IconMassage,
  MathAvg: IconMathAvg,
  MathFunction: IconMathFunction,
  MathMax: IconMathMax,
  MathMin: IconMathMin,
  MathSymbols: IconMathSymbols,
  Math: IconMath,
  Maximize: IconMaximize,
  Meat: IconMeat,
  Medal2: IconMedal2,
  Medal: IconMedal,
  MedicalCross: IconMedicalCross,
  MedicineSyrup: IconMedicineSyrup,
  Menu2: IconMenu2,
  Menu: IconMenu,
  Message2Code: IconMessage2Code,
  Message2Share: IconMessage2Share,
  Message2: IconMessage2,
  MessageCircle2: IconMessageCircle2,
  MessageCircle: IconMessageCircle,
  MessageCode: IconMessageCode,
  MessageDots: IconMessageDots,
  MessageForward: IconMessageForward,
  MessageLanguage: IconMessageLanguage,
  MessagePlus: IconMessagePlus,
  MessageReport: IconMessageReport,
  MessageShare: IconMessageShare,
  Message: IconMessage,
  Messages: IconMessages,
  Meteor: IconMeteor,
  Microphone2: IconMicrophone2,
  Microphone: IconMicrophone,
  Microscope: IconMicroscope,
  Microwave: IconMicrowave,
  MilitaryAward: IconMilitaryAward,
  MilitaryRank: IconMilitaryRank,
  Milk: IconMilk,
  Minimize: IconMinimize,
  MinusVertical: IconMinusVertical,
  Minus: IconMinus,
  Mist: IconMist,
  MoodBoy: IconMoodBoy,
  MoodConfuzed: IconMoodConfuzed,
  MoodCrazyHappy: IconMoodCrazyHappy,
  MoodCry: IconMoodCry,
  MoodEmpty: IconMoodEmpty,
  MoodHappy: IconMoodHappy,
  MoodKid: IconMoodKid,
  MoodNervous: IconMoodNervous,
  MoodNeutral: IconMoodNeutral,
  MoodSad: IconMoodSad,
  MoodSmile: IconMoodSmile,
  MoodSuprised: IconMoodSuprised,
  MoodTongue: IconMoodTongue,
  Moon2: IconMoon2,
  MoonStars: IconMoonStars,
  Moon: IconMoon,
  Moped: IconMoped,
  Motorbike: IconMotorbike,
  Mountain: IconMountain,
  Mouse2: IconMouse2,
  Mouse: IconMouse,
  Movie: IconMovie,
  Mug: IconMug,
  Multiplier05x: IconMultiplier05x,
  Multiplier15x: IconMultiplier15x,
  Multiplier1x: IconMultiplier1x,
  Multiplier2x: IconMultiplier2x,
  Mushroom: IconMushroom,
  Music: IconMusic,
  Network: IconNetwork,
  NewSection: IconNewSection,
  News: IconNews,
  Nfc: IconNfc,
  NoCopyright: IconNoCopyright,
  NoCreativeCommons: IconNoCreativeCommons,
  NoDerivatives: IconNoDerivatives,
  NorthStar: IconNorthStar,
  Note: IconNote,
  Notebook: IconNotebook,
  Notes: IconNotes,
  Notification: IconNotification,
  Number0: IconNumber0,
  Number1: IconNumber1,
  Number2: IconNumber2,
  Number3: IconNumber3,
  Number4: IconNumber4,
  Number5: IconNumber5,
  Number6: IconNumber6,
  Number7: IconNumber7,
  Number8: IconNumber8,
  Number9: IconNumber9,
  Number: IconNumber,
  Numbers: IconNumbers,
  Nurse: IconNurse,
  Octagon: IconOctagon,
  Old: IconOld,
  Olympics: IconOlympics,
  Omega: IconOmega,
  Outbound: IconOutbound,
  Outlet: IconOutlet,
  OvalVertical: IconOvalVertical,
  Oval: IconOval,
  Overline: IconOverline,
  Package: IconPackage,
  PackgeExport: IconPackageExport,
  PackgeImport: IconPackageImport,
  Pacman: IconPacman,
  PageBreak: IconPageBreak,
  Paint: IconPaint,
  Palette: IconPalette,
  PanoramaHorizontal: IconPanoramaHorizontal,
  PanoramaVertical: IconPanoramaVertical,
  PaperBag: IconPaperBag,
  Paperclip: IconPaperclip,
  Parachute: IconParachute,
  Parentheses: IconParentheses,
  Parking: IconParking,
  Paw: IconPaw,
  Peace: IconPeace,
  PencilMinus: IconPencilMinus,
  PencilPlus: IconPencilPlus,
  Pencil: IconPencil,
  Pennant2: IconPennant2,
  Pennant: IconPennant,
  Pentagon: IconPentagon,
  Pepper: IconPepper,
  Percentage: IconPercentage,
  Perspective: IconPerspective,
  PhoneCall: IconPhoneCall,
  PhoneCalling: IconPhoneCalling,
  PhoneCheck: IconPhoneCheck,
  PhoneIncoming: IconPhoneIncoming,
  PhoneOutgoing: IconPhoneOutgoing,
  PhonePause: IconPhonePause,
  PhonePlus: IconPhonePlus,
  PhoneX: IconPhoneX,
  Phone: IconPhone,
  Photo: IconPhoto,
  Physotherapist: IconPhysotherapist,
  PictureInPictureOn: IconPictureInPictureOn,
  PictureInPictureTop: IconPictureInPictureTop,
  PictureInPicture: IconPictureInPicture,
  Pig: IconPig,
  Pill: IconPill,
  Pills: IconPills,
  Pin: IconPin,
  Pinned: IconPinned,
  Pizza: IconPizza,
  PlaneArrival: IconPlaneArrival,
  PlaneDeparture: IconPlaneDeparture,
  PlaneInflight: IconPlaneInflight,
  PlaneTilt: IconPlaneTilt,
  Plane: IconPlane,
  Planet: IconPlanet,
  Plant2: IconPlant2,
  Plant: IconPlant,
  PlayCard: IconPlayCard,
  PlayerEject: IconPlayerEject,
  PlayerPause: IconPlayerPause,
  PlayerPlay: IconPlayerPlay,
  PlayerRecord: IconPlayerRecord,
  PlayerSkipBack: IconPlayerSkipBack,
  PlayerSkipForward: IconPlayerSkipForward,
  PlayerStop: IconPlayerStop,
  PlayerTrackNext: IconPlayerTrackNext,
  PlayerTrackPrev: IconPlayerTrackPrev,
  PlaylistAdd: IconPlaylistAdd,
  PlaylistX: IconPlaylistX,
  Playlist: IconPlaylist,
  PlugConnectedX: IconPlugConnectedX,
  PlugConnected: IconPlugConnected,
  PlugX: IconPlugX,
  Plug: IconPlug,
  Plus: IconPlus,
  Podium: IconPodium,
  Point: IconPoint,
  Pointer: IconPointer,
  Pokeball: IconPokeball,
  Polaroid: IconPolaroid,
  Polygon: IconPolygon,
  Poo: IconPoo,
  Pool: IconPool,
  Power: IconPower,
  Pray: IconPray,
  PremiumRights: IconPremiumRights,
  Prescription: IconPrescription,
  PresentationAnalytics: IconPresentationAnalytics,
  Presentation: IconPresentation,
  Printer: IconPrinter,
  Prison: IconPrison,
  Prompt: IconPrompt,
  Propeller: IconPropeller,
  Puzzle2: IconPuzzle2,
  Puzzle: IconPuzzle,
  Pyramid: IconPyramid,
  Qrcode: IconQrcode,
  QuestionMark: IconQuestionMark,
  Quote: IconQuote,
  Radar2: IconRadar2,
  Radar: IconRadar,
  Radio: IconRadio,
  Radioactive: IconRadioactive,
  RadiusBottomLeft: IconRadiusBottomLeft,
  RadiusBottomRight: IconRadiusBottomRight,
  RadiusTopLeft: IconRadiusTopLeft,
  RadiusTopRight: IconRadiusTopRight,
  Rainbow: IconRainbow,
  Rating12Plus: IconRating12Plus,
  Rating14Plus: IconRating14Plus,
  Rating16Plus: IconRating16Plus,
  Rating18Plus: IconRating18Plus,
  Rating21Plus: IconRating21Plus,
  Receipt2: IconReceipt2,
  ReceiptRefund: IconReceiptRefund,
  ReceiptTax: IconReceiptTax,
  Receipt: IconReceipt,
  Recharging: IconRecharging,
  RecordMail: IconRecordMail,
  RectangleVertical: IconRectangleVertical,
  Rectangle: IconRectangle,
  Recycle: IconRecycle,
  RefreshAlert: IconRefreshAlert,
  RefreshDot: IconRefreshDot,
  Refresh: IconRefresh,
  Registered: IconRegistered,
  RelationManyToMany: IconRelationManyToMany,
  RelationOneToMany: IconRelationOneToMany,
  RelationOneToOne: IconRelationOneToOne,
  RepeatOnce: IconRepeatOnce,
  Repeat: IconRepeat,
  Replace: IconReplace,
  ReportAnalytics: IconReportAnalytics,
  ReportMedical: IconReportMedical,
  ReportMoney: IconReportMoney,
  ReportSearch: IconReportSearch,
  Report: IconReport,
  Resize: IconResize,
  Ripple: IconRipple,
  RoadSign: IconRoadSign,
  Road: IconRoad,
  Robot: IconRobot,
  Rocket: IconRocket,
  RollerSkating: IconRollerSkating,
  Rollercoaster: IconRollercoaster,
  Rotate2: IconRotate2,
  Rotate360: IconRotate360,
  RotateClockwise2: IconRotateClockwise2,
  RotateClockwise: IconRotateClockwise,
  RotateDot: IconRotateDot,
  RotateRectangle: IconRotateRectangle,
  Rotate: IconRotate,
  Route: IconRoute,
  Router: IconRouter,
  RowInsertBottom: IconRowInsertBottom,
  RowInsertTop: IconRowInsertTop,
  Rss: IconRss,
  Ruler2: IconRuler2,
  Ruler3: IconRuler3,
  RulerMeasure: IconRulerMeasure,
  Ruler: IconRuler,
  Run: IconRun,
  Sailboat: IconSailboat,
  Salt: IconSalt,
  Satellite: IconSatellite,
  Sausage: IconSausage,
  ScaleOutline: IconScaleOutline,
  Scale: IconScale,
  ScanEye: IconScanEye,
  Scan: IconScan,
  Schema: IconSchema,
  School: IconSchool,
  Scissors: IconScissors,
  ScooterElectric: IconScooterElectric,
  Scooter: IconScooter,
  ScreenShare: IconScreenShare,
  Screenshot: IconScreenshot,
  Scribble: IconScribble,
  ScubaMask: IconScubaMask,
  Search: IconSearch,
  SectionSign: IconSectionSign,
  Section: IconSection,
  Seeding: IconSeeding,
  Select: IconSelect,
  Selector: IconSelector,
  Send: IconSend,
  Seo: IconSeo,
  SeparatorHorizontal: IconSeparatorHorizontal,
  SeparatorVertical: IconSeparatorVertical,
  Separator: IconSeparator,
  Server2: IconServer2,
  Server: IconServer,
  Servicemark: IconServicemark,
  SettingsAutomation: IconSettingsAutomation,
  Settings: IconSettings,
  Shadow: IconShadow,
  Shape2: IconShape2,
  Shape3: IconShape3,
  Shape: IconShape,
  Share: IconShare,
  ShieldCheck: IconShieldCheck,
  ShieldCheckered: IconShieldCheckered,
  ShieldChevron: IconShieldChevron,
  ShieldLock: IconShieldLock,
  ShieldX: IconShieldX,
  Shield: IconShield,
  Ship: IconShip,
  ShirtSport: IconShirtSport,
  Shirt: IconShirt,
  Shoe: IconShoe,
  ShoppingCartDiscount: IconShoppingCartDiscount,
  ShoppingCartPlus: IconShoppingCartPlus,
  ShoppingCartX: IconShoppingCartX,
  ShoppingCart: IconShoppingCart,
  Shovel: IconShovel,
  Shredder: IconShredder,
  SignLeft: IconSignLeft,
  SignRight: IconSignRight,
  Signal3g: IconSignal3g,
  Signal4gPlus: IconSignal4gPlus,
  Signal4g: IconSignal4g,
  Signal5g: IconSignal5g,
  Signature: IconSignature,
  Sitemap: IconSitemap,
  Skateboard: IconSkateboard,
  Skull: IconSkull,
  Sleigh: IconSleigh,
  Slice: IconSlice,
  Slideshow: IconSlideshow,
  SmartHome: IconSmartHome,
  SmokingNo: IconSmokingNo,
  Smoking: IconSmoking,
  Snowflake: IconSnowflake,
  Snowman: IconSnowman,
  SoccerField: IconSoccerField,
  Social: IconSocial,
  Sock: IconSock,
  Sofa: IconSofa,
  SortAscending2: IconSortAscending2,
  SortAscendingLetters: IconSortAscendingLetters,
  SortAscendingNumbers: IconSortAscendingNumbers,
  SortAscending: IconSortAscending,
  SortDescending2: IconSortDescending2,
  SortDescendingLetters: IconSortDescendingLetters,
  SortDescendingNumbers: IconSortDescendingNumbers,
  SortDescending: IconSortDescending,
  Sos: IconSos,
  Soup: IconSoup,
  Space: IconSpace,
  SpacingHorizontal: IconSpacingHorizontal,
  SpacingVertical: IconSpacingVertical,
  Spade: IconSpade,
  Speakerphone: IconSpeakerphone,
  Speedboat: IconSpeedboat,
  Spider: IconSpider,
  Spiral: IconSpiral,
  SportBillard: IconSportBillard,
  Spy: IconSpy,
  Square0: IconSquareF0,
  Square1: IconSquareF1,
  Square2: IconSquareF2,
  Square3: IconSquareF3,
  Square4: IconSquareF4,
  Square5: IconSquareF5,
  Square6: IconSquareF6,
  Square7: IconSquareF7,
  Square8: IconSquareF8,
  Square9: IconSquareF9,
  SquareAsterisk: IconSquareAsterisk,
  SquareCheck: IconSquareCheck,
  SquareDot: IconSquareDot,
  SquareForbid2: IconSquareForbid2,
  SquareForbid: IconSquareForbid,
  SquareHalf: IconSquareHalf,
  SquareMinus: IconSquareMinus,
  SquarePlus: IconSquarePlus,
  SquareRoot2: IconSquareRoot2,
  SquareRoot: IconSquareRoot,
  SquareRotatedForbid2: IconSquareRotatedForbid2,
  SquareRotatedForbid: IconSquareRotatedForbid,
  SquareRotated: IconSquareRotated,
  SquareToggleHorizontal: IconSquareToggleHorizontal,
  SquareToggle: IconSquareToggle,
  SquareX: IconSquareX,
  Square: IconSquare,
  SquaresDiagonal: IconSquaresDiagonal,
  SquaresFilled: IconSquaresFilled,
  Stack2: IconStack2,
  Stack3: IconStack3,
  StackPop: IconStackPop,
  StackPush: IconStackPush,
  Stack: IconStack,
  StairsDown: IconStairsDown,
  StairsUp: IconStairsUp,
  Stairs: IconStairs,
  StarHalf: IconStarHalf,
  Star: IconStar,
  Stars: IconStars,
  Steam: IconSteam,
  SteeringWheel: IconSteeringWheel,
  StepInto: IconStepInto,
  StepOut: IconStepOut,
  Stethoscope: IconStethoscope,
  Sticker: IconSticker,
  Storm: IconStorm,
  Strikethrough: IconStrikethrough,
  Submarine: IconSubmarine,
  Subscript: IconSubscript,
  Subtask: IconSubtask,
  Sum: IconSum,
  SunHigh: IconSunHigh,
  SunLow: IconSunLow,
  SunWind: IconSunWind,
  Sun: IconSun,
  Sunglasses: IconSunglasses,
  Sunrise: IconSunrise,
  Sunset2: IconSunset2,
  Sunset: IconSunset,
  Superscript: IconSuperscript,
  Svg: IconSvg,
  Swimming: IconSwimming,
  Switch2: IconSwitch2,
  Switch3: IconSwitch3,
  SwitchHorizontal: IconSwitchHorizontal,
  SwitchVertical: IconSwitchVertical,
  Switch: IconSwitch,
  Sword: IconSword,
  Swords: IconSwords,
  TableAlias: IconTableAlias,
  TableExport: IconTableExport,
  TableImport: IconTableImport,
  TableOptions: IconTableOptions,
  TableShortcut: IconTableShortcut,
  Table: IconTable,
  Tag: IconTag,
  Tags: IconTags,
  Tallymark1: IconTallymark1,
  Tallymark2: IconTallymark2,
  Tallymark3: IconTallymark3,
  Tallymark4: IconTallymark4,
  Tallymarks: IconTallymarks,
  Tank: IconTank,
  Target: IconTarget,
  Telescope: IconTelescope,
  TemperatureCelsius: IconTemperatureCelsius,
  TemperatureFahrenheit: IconTemperatureFahrenheit,
  TemperatureMinus: IconTemperatureMinus,
  TemperaturePlus: IconTemperaturePlus,
  Temperature: IconTemperature,
  Template: IconTemplate,
  Tent: IconTent,
  Terminal2: IconTerminal2,
  Terminal: IconTerminal,
  TestPipe2: IconTestPipe2,
  TestPipe: IconTestPipe,
  TextDecrease: IconTextDecrease,
  TextDirectionLtr: IconTextDirectionLtr,
  TextDirectionRtl: IconTextDirectionRtl,
  TextIncrease: IconTextIncrease,
  TextRecognition: IconTextRecognition,
  TextResize: IconTextResize,
  TextWrapDisabled: IconTextWrapDisabled,
  TextWrap: IconTextWrap,
  Thermometer: IconThermometer,
  ThumbDown: IconThumbDown,
  ThumbUp: IconThumbUp,
  Ticket: IconTicket,
  Tie: IconTie,
  TiltShift: IconTiltShift,
  Timeline: IconTimeline,
  Tir: IconTir,
  ToggleLeft: IconToggleLeft,
  ToggleRight: IconToggleRight,
  ToiletPaper: IconToiletPaper,
  Tool: IconTool,
  ToolsKitchen2: IconToolsKitchen2,
  ToolsKitchen: IconToolsKitchen,
  Tools: IconTools,
  Tornado: IconTornado,
  Tournament: IconTournament,
  Track: IconTrack,
  Tractor: IconTractor,
  Trademark: IconTrademark,
  TrafficCone: IconTrafficCone,
  TrafficLights: IconTrafficLights,
  Train: IconTrain,
  TransferIn: IconTransferIn,
  TransferOut: IconTransferOut,
  TrashX: IconTrashX,
  Trash: IconTrash,
  Tree: IconTree,
  Trees: IconTrees,
  TrendingDown2: IconTrendingDown2,
  TrendingDown3: IconTrendingDown3,
  TrendingDown: IconTrendingDown,
  TrendingUp2: IconTrendingUp2,
  TrendingUp3: IconTrendingUp3,
  TrendingUp: IconTrendingUp,
  TriangleInverted: IconTriangleInverted,
  TriangleSquareCircle: IconTriangleSquareCircle,
  Triangle: IconTriangle,
  Triangles: IconTriangles,
  Trident: IconTrident,
  Trophy: IconTrophy,
  TruckDelivery: IconTruckDelivery,
  TruckLoading: IconTruckLoading,
  TruckReturn: IconTruckReturn,
  Truck: IconTruck,
  Typography: IconTypography,
  Ufo: IconUfo,
  Umbrella: IconUmbrella,
  Underline: IconUnderline,
  Unlink: IconUnlink,
  Upload: IconUpload,
  Urgent: IconUrgent,
  Usb: IconUsb,
  UserCheck: IconUserCheck,
  UserCircle: IconUserCircle,
  UserExclamation: IconUserExclamation,
  UserMinus: IconUserMinus,
  UserPlus: IconUserPlus,
  UserSearch: IconUserSearch,
  UserX: IconUserX,
  User: IconUser,
  Users: IconUsers,
  VaccineBottle: IconVaccineBottle,
  Vaccine: IconVaccine,
  Variable: IconVariable,
  VectorBezier2: IconVectorBezier2,
  VectorBezier: IconVectorBezier,
  VectorTriangle: IconVectorTriangle,
  Vector: IconVector,
  Venus: IconVenus,
  Versions: IconVersions,
  VideoMinus: IconVideoMinus,
  VideoPlus: IconVideoPlus,
  Video: IconVideo,
  View360: IconView360,
  Viewfinder: IconViewfinder,
  ViewportNarrow: IconViewportNarrow,
  ViewportWide: IconViewportWide,
  Vinyl: IconVinyl,
  VirusSearch: IconVirusSearch,
  Virus: IconVirus,
  Vocabulary: IconVocabulary,
  Volume2: IconVolume2,
  Volume3: IconVolume3,
  Volume: IconVolume,
  Walk: IconWalk,
  Wall: IconWall,
  Wallet: IconWallet,
  Wallpaper: IconWallpaper,
  Wand: IconWand,
  WashMachine: IconWashMachine,
  WaveSawTool: IconWaveSawTool,
  WaveSine: IconWaveSine,
  WaveSquare: IconWaveSquare,
  Webhook: IconWebhook,
  Wheelchair: IconWheelchair,
  Wifi0: IconWifi0,
  Wifi1: IconWifi1,
  Wifi2: IconWifi2,
  Wifi: IconWifi,
  Wind: IconWind,
  Windmill: IconWindmill,
  WindowMaximize: IconWindowMaximize,
  WindowMinimize: IconWindowMinimize,
  Window: IconWindow,
  Windsock: IconWindsock,
  WiperWash: IconWiperWash,
  Wiper: IconWiper,
  Woman: IconWoman,
  WorldDownload: IconWorldDownload,
  WorldLatitude: IconWorldLatitude,
  WorldLongitude: IconWorldLongitude,
  WorldUpload: IconWorldUpload,
  World: IconWorld,
  WreckingBall: IconWreckingBall,
  WritingSign: IconWritingSign,
  Writing: IconWriting,
  X: IconX,
  YinYang: IconYinYang,
  Yoga: IconYoga,
  Zeppelin: IconZeppelin,
  ZodiacAquarius: IconZodiacAquarius,
  ZodiacAries: IconZodiacAries,
  ZodiacCancer: IconZodiacCancer,
  ZodiacCapricorn: IconZodiacCapricorn,
  ZodiacGemini: IconZodiacGemini,
  ZodiacLeo: IconZodiacLeo,
  ZodiacLibra: IconZodiacLibra,
  ZodiacPisces: IconZodiacPisces,
  ZodiacSagittarius: IconZodiacSagittarius,
  ZodiacScorpio: IconZodiacScorpio,
  ZodiacTaurus: IconZodiacTaurus,
  ZodiacVirgo: IconZodiacVirgo,
  ZoomCancel: IconZoomCancel,
  ZoomCheck: IconZoomCheck,
  ZoomCode: IconZoomCode,
  ZoomExclamation: IconZoomExclamation,
  ZoomInArea: IconZoomInArea,
  ZoomIn: IconZoomIn,
  ZoomMoney: IconZoomMoney,
  ZoomOutArea: IconZoomOutArea,
  ZoomOut: IconZoomOut,
  ZoomPan: IconZoomPan,
  ZoomQuestion: IconZoomQuestion,
  ZoomReset: IconZoomReset,
  Zzz: IconZzz
}
