import { IconProps } from "solid-icons"
import {
  Tb3dCubeSphere,
  Tb3dRotate,
  TbAbacus,
  TbAccessPoint,
  TbAccessible,
  TbActivityHeartbeat,
  TbActivity,
  TbAd2,
  TbAd,
  TbAddressBook,
  TbAdjustments,
  TbAerialLift,
  TbAffiliate,
  TbAlarm,
  TbAlbum,
  TbAlertCircle,
  TbAlertOctagon,
  TbAlertTriangle,
  TbAlien,
  TbAlignLeft,
  TbAlphabetCyrillic,
  TbAlphabetGreek,
  TbAlphabetLatin,
  TbAmbulance,
  TbAmpersand,
  TbAnchor,
  TbAngle,
  TbAnkh,
  TbAntennaBars3,
  TbAntenna,
  TbAperture,
  TbApiApp,
  TbApi,
  TbAppWindow,
  TbApple,
  TbApps,
  TbArchive,
  TbArmchair2,
  TbArmchair,
  TbArrowsCross,
  TbArrowsDiagonal2,
  TbArrowsDiagonalMinimize2,
  TbArrowsDiagonalMinimize,
  TbArrowsDiagonal,
  TbArrowsDoubleNeSw,
  TbArrowsDoubleNwSe,
  TbArrowsDoubleSeNw,
  TbArrowsDoubleSwNe,
  TbArrowsDownUp,
  TbArrowsDown,
  TbArrowsExchange2,
  TbArrowsExchange,
  TbArrowsHorizontal,
  TbArrowsJoin2,
  TbArrowsJoin,
  TbArrowsLeftDown,
  TbArrowsLeftRight,
  TbArrowsLeft,
  TbArrowsMaximize,
  TbArrowsMinimize,
  TbArrowsMoveHorizontal,
  TbArrowsMoveVertical,
  TbArrowsMove,
  TbArrowsRandom,
  TbArrowsRightDown,
  TbArrowsRightLeft,
  TbArrowsRight,
  TbArrowsShuffle2,
  TbArrowsShuffle,
  TbArrowsSort,
  TbArrowsSplit2,
  TbArrowsSplit,
  TbArrowsUpDown,
  TbArrowsUpLeft,
  TbArrowsUpRight,
  TbArrowsUp,
  TbArrowsVertical,
  TbArtboard,
  TbArticle,
  TbAspectRatio,
  TbAssembly,
  TbAsset,
  TbAsteriskSimple,
  TbAsterisk,
  TbAt,
  TbAtom2,
  TbAtom,
  TbAugmentedReality,
  TbAward,
  TbAxe,
  TbAxisX,
  TbAxisY,
  TbBabyCarriage,
  TbBackhoe,
  TbBackpack,
  TbBackspace,
  TbBadge,
  TbBadges,
  TbBallAmericanFootball,
  TbBallBaseball,
  TbBallBasketball,
  TbBallBowling,
  TbBallFootball,
  TbBallTennis,
  TbBallVolleyball,
  TbBalloon,
  TbBallpen,
  TbBan,
  TbBandage,
  TbBarbell,
  TbBarcode,
  TbBarrel,
  TbBarrierBlock,
  TbBaseline,
  TbBasket,
  TbBat,
  TbBath,
  TbBattery4,
  TbBatteryAutomotive,
  TbBatteryCharging,
  TbBatteryEco,
  TbBattery,
  TbBeach,
  TbBed,
  TbBeer,
  TbBellMinus,
  TbBellPlus,
  TbBellRinging2,
  TbBellRinging,
  TbBellSchool,
  TbBellX,
  TbBellZ,
  TbBell,
  TbBible,
  TbBike,
  TbBinary,
  TbBiohazard,
  TbBlockquote,
  TbBluetoothConnected,
  TbBluetoothX,
  TbBluetooth,
  TbBlur,
  TbBold,
  TbBolt,
  TbBone,
  TbBook2,
  TbBookDownload,
  TbBookUpload,
  TbBook,
  TbBookmark,
  TbBookmarks,
  TbBooks,
  TbBorderTop,
  TbBorderVertical,
  TbBottle,
  TbBow,
  TbBoxMargin,
  TbBoxModel2,
  TbBoxModel,
  TbBoxMultiple,
  TbBoxPadding,
  TbBox,
  TbBraces,
  TbBracketsContainEnd,
  TbBracketsContainStart,
  TbBracketsContain,
  TbBrackets,
  TbBread,
  TbBriefcase,
  TbBrightness2,
  TbBrightnessDown,
  TbBrightnessHalf,
  TbBrightnessUp,
  TbBrightness,
  TbBroadcast,
  TbBrowserCheck,
  TbBrowserPlus,
  TbBrowserX,
  TbBrowser,
  TbBrush,
  TbBucket,
  TbBug,
  TbBuildingArch,
  TbBuildingBank,
  TbBuildingBridge2,
  TbBuildingBridge,
  TbBuildingCarousel,
  TbBuildingCastle,
  TbBuildingChurch,
  TbBuildingCommunity,
  TbBuildingCottage,
  TbBuildingFactory2,
  TbBuildingFactory,
  TbBuildingFortress,
  TbBuildingHospital,
  TbBuildingLighthouse,
  TbBuildingMonument,
  TbBuildingPavilion,
  TbBuildingSkyscraper,
  TbBuildingStore,
  TbBuildingWarehouse,
  TbBuilding,
  TbBulb,
  TbBulldozer,
  TbBus,
  TbBusinessplan,
  TbButterfly,
  TbBrandCSharp,
  TbCactus,
  TbCake,
  TbCalculator,
  TbCalendarEvent,
  TbCalendarMinus,
  TbCalendarPlus,
  TbCalendarStats,
  TbCalendarTime,
  TbCalendar,
  TbCameraMinus,
  TbCameraPlus,
  TbCameraRotate,
  TbCameraSelfie,
  TbCamera,
  TbCandle,
  TbCandy,
  TbCapture,
  TbCarCrane,
  TbCarCrash,
  TbCar,
  TbCaravan,
  TbCardboards,
  TbCaretDown,
  TbCaretLeft,
  TbCaretRight,
  TbCaretUp,
  TbCarrot,
  TbCashBanknote,
  TbCash,
  TbCast,
  TbCategory2,
  TbCategory,
  TbCe,
  TbCellSignal1,
  TbCellSignal2,
  TbCellSignal3,
  TbCellSignal4,
  TbCellSignal5,
  TbCell,
  TbCertificate2,
  TbCertificate,
  TbChargingPile,
  TbChartArcs3,
  TbChartArcs,
  TbChartAreaLine,
  TbChartArea,
  TbChartArrowsVertical,
  TbChartArrows,
  TbChartBar,
  TbChartBubble,
  TbChartCandle,
  TbChartCircles,
  TbChartDonut2,
  TbChartDonut3,
  TbChartDonut4,
  TbChartDonut,
  TbChartDots2,
  TbChartDots3,
  TbChartDots,
  TbChartInfographic,
  TbChartLine,
  TbChartPie2,
  TbChartPie3,
  TbChartPie4,
  TbChartPie,
  TbChartRadar,
  TbCheck,
  TbCheckbox,
  TbChecklist,
  TbChecks,
  TbCheckupList,
  TbCheese,
  TbChefHat,
  TbChevronDownLeft,
  TbChevronDownRight,
  TbChevronDown,
  TbChevronLeft,
  TbChevronRight,
  TbChevronUpLeft,
  TbChevronUpRight,
  TbChevronUp,
  TbChevronsDownLeft,
  TbChevronsDownRight,
  TbChevronsDown,
  TbChevronsLeft,
  TbChevronsRight,
  TbChevronsUpLeft,
  TbChevronsUpRight,
  TbChevronsUp,
  TbChristmasTree,
  TbCircleNumber0,
  TbCircleNumber1,
  TbCircleNumber2,
  TbCircleNumber3,
  TbCircleNumber4,
  TbCircleNumber5,
  TbCircleNumber6,
  TbCircleNumber7,
  TbCircleNumber8,
  TbCircleNumber9,
  TbCircleCheck,
  TbCircleDashed,
  TbCircleDot,
  TbCircleDotted,
  TbCircleHalf2,
  TbCircleHalfVertical,
  TbCircleHalf,
  TbCircleMinus,
  TbCirclePlus,
  TbCircleRectangle,
  TbCircleSquare,
  TbCircleTriangle,
  TbCircleX,
  TbCircle,
  TbCircles,
  TbCircuitAmmeter,
  TbCircuitBattery,
  TbCircuitBulb,
  TbCircuitCapacitorPolarized,
  TbCircuitCapacitor,
  TbCircuitCellPlus,
  TbCircuitCell,
  TbCircuitChangeover,
  TbCircuitDiodeZener,
  TbCircuitDiode,
  TbCircuitGroundDigital,
  TbCircuitGround,
  TbCircuitInductor,
  TbCircuitMotor,
  TbCircuitPushbutton,
  TbCircuitResistor,
  TbCircuitSwitchClosed,
  TbCircuitSwitchOpen,
  TbCircuitVoltmeter,
  TbClearAll,
  TbClearFormatting,
  TbClick,
  TbClipboardCheck,
  TbClipboardList,
  TbClipboardPlus,
  TbClipboardText,
  TbClipboardX,
  TbClipboard,
  TbClock2,
  TbClock,
  TbClothesRack,
  TbCloudComputing,
  TbCloudDataConnection,
  TbCloudDownload,
  TbCloudFog,
  TbCloudLockOpen,
  TbCloudLock,
  TbCloudRain,
  TbCloudSnow,
  TbCloudStorm,
  TbCloudUpload,
  TbCloud,
  TbClover2,
  TbClover,
  TbClubs,
  TbCodeMinus,
  TbCodePlus,
  TbCoin,
  TbColorPicker,
  TbColorSwatch,
  TbColumnInsertLeft,
  TbColumnInsertRight,
  TbColumns,
  TbComet,
  TbCommand,
  TbCompass,
  TbComponents,
  TbCone2,
  TbCone,
  TbConfetti,
  TbContainer,
  TbContrast2,
  TbContrast,
  TbCookie,
  TbCopy,
  TbCopyleft,
  TbCopyright,
  TbCornerDownLeftDouble,
  TbCornerDownLeft,
  TbCornerDownRightDouble,
  TbCornerDownRight,
  TbCornerLeftDownDouble,
  TbCornerLeftDown,
  TbCornerLeftUpDouble,
  TbCornerLeftUp,
  TbCornerRightDownDouble,
  TbCornerRightDown,
  TbCornerRightUpDouble,
  TbCornerRightUp,
  TbCornerUpLeftDouble,
  TbCornerUpLeft,
  TbCornerUpRightDouble,
  TbCornerUpRight,
  TbCpu2,
  TbCpu,
  TbCrane,
  TbCreativeCommonsBy,
  TbCreativeCommonsNc,
  TbCreativeCommonsNd,
  TbCreativeCommonsSa,
  TbCreativeCommonsZero,
  TbCreativeCommons,
  TbCreditCard,
  TbCricket,
  TbCrop,
  TbCross,
  TbCrosshair,
  TbCrown,
  TbCrutches,
  TbCup,
  TbCurling,
  TbCurlyLoop,
  TbCurrencyBahraini,
  TbCurrencyBaht,
  TbCurrencyBitcoin,
  TbCurrencyCent,
  TbCurrencyDinar,
  TbCurrencyDirham,
  TbCurrencyDogecoin,
  TbCurrencyDollarAustralian,
  TbCurrencyDollarCanadian,
  TbCurrencyDollarSingapore,
  TbCurrencyDollar,
  TbCurrencyEthereum,
  TbCurrencyEuro,
  TbCurrencyForint,
  TbCurrencyFrank,
  TbCurrencyKroneCzech,
  TbCurrencyKroneDanish,
  TbCurrencyKroneSwedish,
  TbCurrencyLeu,
  TbCurrencyLira,
  TbCurrencyLitecoin,
  TbCurrencyNaira,
  TbCurrencyPound,
  TbCurrencyReal,
  TbCurrencyRenminbi,
  TbCurrencyRipple,
  TbCurrencyRiyal,
  TbCurrencyRubel,
  TbCurrencyRupee,
  TbCurrencyShekel,
  TbCurrencyTaka,
  TbCurrencyTugrik,
  TbCurrencyWon,
  TbCurrencyYen,
  TbCurrencyZloty,
  TbCurrency,
  TbCurrentLocation,
  TbCursorText,
  TbCut,
  TbDashboard,
  TbDatabaseExport,
  TbDatabaseImport,
  TbDatabase,
  TbDentalBroken,
  TbDental,
  TbDetails,
  TbDeviceAnalytics,
  TbDeviceAudioTape,
  TbDeviceCameraPhone,
  TbDeviceCctv,
  TbDeviceComputerCamera,
  TbDeviceDesktopAnalytics,
  TbDeviceDesktop,
  TbDeviceFloppy,
  TbDeviceGamepad2,
  TbDeviceGamepad,
  TbDeviceHeartMonitor,
  TbDeviceLaptop,
  TbDeviceMobileCharging,
  TbDeviceMobileMessage,
  TbDeviceMobileRotated,
  TbDeviceMobileVibration,
  TbDeviceMobile,
  TbDeviceNintendo,
  TbDeviceSpeaker,
  TbDeviceTablet,
  TbDeviceTvOld,
  TbDeviceTv,
  TbDeviceWatchStats2,
  TbDeviceWatchStats,
  TbDeviceWatch,
  TbDevices2,
  TbDevicesPc,
  TbDevices,
  TbDialpad,
  TbDiamond,
  TbDiamonds,
  TbDice1,
  TbDice2,
  TbDice3,
  TbDice4,
  TbDice5,
  TbDice6,
  TbDice,
  TbDimensions,
  TbDirectionHorizontal,
  TbDirectionSign,
  TbDirection,
  TbDirections,
  TbDisabled2,
  TbDisabled,
  TbDisc,
  TbDiscount2,
  TbDiscountCheck,
  TbDiscount,
  TbDivide,
  TbDna2,
  TbDna,
  TbDogBowl,
  TbDoorEnter,
  TbDoorExit,
  TbDoor,
  TbDotsCircleHorizontal,
  TbDotsDiagonal2,
  TbDotsDiagonal,
  TbDotsVertical,
  TbDots,
  TbDownload,
  TbDragDrop2,
  TbDragDrop,
  TbDrone,
  TbDropCircle,
  TbDropletFilled2,
  TbDropletFilled,
  TbDropletHalf2,
  TbDropletHalf,
  TbDroplet,
  TbEar,
  TbEditCircle,
  TbEdit,
  TbEgg,
  TbElevator,
  TbEmergencyBed,
  TbEmphasis,
  TbEngine,
  TbEqualNot,
  TbEqual,
  TbEraser,
  TbError404,
  TbExchange,
  TbExclamationMark,
  TbExplicit,
  TbExposure,
  TbExternalLink,
  TbEyeCheck,
  TbEyeTable,
  TbEye,
  TbEyeglass2,
  TbEyeglass,
  TbFaceIdError,
  TbFaceId,
  TbFaceMask,
  TbFall,
  TbFeather,
  TbFence,
  TbFidgetSpinner,
  TbFile3d,
  TbFileAlert,
  TbFileAnalytics,
  TbFileArrowLeft,
  TbFileArrowRight,
  TbFileBarcode,
  TbFileCertificate,
  TbFileChart,
  TbFileCheck,
  TbFileCode2,
  TbFileCode,
  TbFileDatabase,
  TbFileDescription,
  TbFileDiff,
  TbFileDigit,
  TbFileDislike,
  TbFileDollar,
  TbFileDots,
  TbFileDownload,
  TbFileEuro,
  TbFileExport,
  TbFileHorizontal,
  TbFileImport,
  TbFileInfo,
  TbFileInvoice,
  TbFileLike,
  TbFileMinus,
  TbFileMusic,
  TbFilePencil,
  TbFilePhone,
  TbFilePlus,
  TbFilePower,
  TbFileReport,
  TbFileRss,
  TbFileScissors,
  TbFileSearch,
  TbFileSettings,
  TbFileShredder,
  TbFileSignal,
  TbFileSpreadsheet,
  TbFileStar,
  TbFileSymlink,
  TbFileText,
  TbFileTime,
  TbFileTypography,
  TbFileUnknown,
  TbFileUpload,
  TbFileVector,
  TbFileX,
  TbFileZip,
  TbFile,
  TbFiles,
  TbFilter,
  TbFingerprint,
  TbFiretruck,
  TbFirstAidKit,
  TbFishBone,
  TbFishHook,
  TbFish,
  TbFlag2,
  TbFlag3,
  TbFlag,
  TbFlame,
  TbFlare,
  TbFlask2,
  TbFlask,
  TbFlipHorizontal,
  TbFlipVertical,
  TbFloatCenter,
  TbFloatLeft,
  TbFloatNone,
  TbFloatRight,
  TbFlower,
  TbFocus2,
  TbFocusCentered,
  TbFocus,
  TbFoldDown,
  TbFoldUp,
  TbFold,
  TbFolderMinus,
  TbFolderPlus,
  TbFolderX,
  TbFolder,
  TbFolders,
  TbForbid2,
  TbForbid,
  TbForklift,
  TbForms,
  TbFountain,
  TbFrame,
  TbFreeRights,
  TbFridge,
  TbFriends,
  TbFunction,
  TbGardenCart,
  TbGasStation,
  TbGauge,
  TbGavel,
  TbGenderAgender,
  TbGenderAndrogyne,
  TbGenderBigender,
  TbGenderDemiboy,
  TbGenderDemigirl,
  TbGenderEpicene,
  TbGenderFemale,
  TbGenderFemme,
  TbGenderGenderfluid,
  TbGenderGenderless,
  TbGenderGenderqueer,
  TbGenderHermaphrodite,
  TbGenderIntergender,
  TbGenderMale,
  TbGenderNeutrois,
  TbGenderThird,
  TbGenderTransgender,
  TbGenderTrasvesti,
  TbGeometry,
  TbGhost,
  TbGif,
  TbGift,
  TbGitBranch,
  TbGitCommit,
  TbGitCompare,
  TbGitFork,
  TbGitMerge,
  TbGitPullRequestClosed,
  TbGitPullRequestDraft,
  TbGitPullRequest,
  TbGizmo,
  TbGlassFull,
  TbGlass,
  TbGlobe,
  TbGolf,
  TbGps,
  TbGrain,
  TbGraph,
  TbGridDots,
  TbGridPattern,
  TbGrill,
  TbGripHorizontal,
  TbGripVertical,
  TbGrowth,
  TbH1,
  TbH2,
  TbH3,
  TbH4,
  TbH5,
  TbH6,
  TbHammer,
  TbHandClick,
  TbHandFinger,
  TbHandGrab,
  TbHandLittleFinger,
  TbHandMiddleFinger,
  TbHandMove,
  TbHandRingFinger,
  TbHandRock,
  TbHandStop,
  TbHandThreeFingers,
  TbHandTwoFingers,
  TbHanger2,
  TbHanger,
  TbHash,
  TbHaze,
  TbHeading,
  TbHeadphones,
  TbHeadset,
  TbHealthRecognition,
  TbHeartBroken,
  TbHeartHandshake,
  TbHeartMinus,
  TbHeartPlus,
  TbHeartRateMonitor,
  TbHeart,
  TbHeartbeat,
  TbHelicopterLanding,
  TbHelicopter,
  TbHelmet,
  TbHelp,
  TbHexagon,
  TbHexagons,
  TbHierarchy2,
  TbHierarchy3,
  TbHierarchy,
  TbHighlight,
  TbHistoryToggle,
  TbHistory,
  TbHome2,
  TbHome,
  TbHorseToy,
  TbHotelService,
  TbHourglassEmpty,
  TbHourglassHigh,
  TbHourglassLow,
  TbHourglass,
  TbIceCream2,
  TbIceCream,
  TbIceSkating,
  TbIcons,
  TbIdBadge2,
  TbIdBadge,
  TbId,
  TbInbox,
  TbIndentDecrease,
  TbIndentIncrease,
  TbInfinity,
  TbInfoCircle,
  TbInfoSquare,
  TbItalic,
  TbJewishStar,
  TbJumpRope,
  TbKarate,
  TbKayak,
  TbKering,
  TbKey,
  TbKeyboardHide,
  TbKeyboardShow,
  TbKeyboard,
  TbLadder,
  TbLamp2,
  TbLamp,
  TbLanguageHiragana,
  TbLanguageKatakana,
  TbLanguage,
  TbLasso,
  TbLayersDifference,
  TbLayersIntersect2,
  TbLayersIntersect,
  TbLayersLinked,
  TbLayersSubtract,
  TbLayersUnion,
  TbLayout2,
  TbLayoutAlignBottom,
  TbLayoutAlignCenter,
  TbLayoutAlignLeft,
  TbLayoutAlignMiddle,
  TbLayoutAlignRight,
  TbLayoutAlignTop,
  TbLayoutBoardSplit,
  TbLayoutBoard,
  TbLayoutBottombarCollapse,
  TbLayoutBottombarExpand,
  TbLayoutBottombar,
  TbLayoutCards,
  TbLayoutColumns,
  TbLayoutDashboard,
  TbLayoutDistributeHorizontal,
  TbLayoutDistributeVertical,
  TbLayoutGridAdd,
  TbLayoutGrid,
  TbLayoutKanban,
  TbLayoutList,
  TbLayoutNavbarCollapse,
  TbLayoutNavbarExpand,
  TbLayoutNavbar,
  TbLayoutRows,
  TbLayoutSidebarLeftCollapse,
  TbLayoutSidebarLeftExpand,
  TbLayoutSidebarRightCollapse,
  TbLayoutSidebarRightExpand,
  TbLayoutSidebarRight,
  TbLayoutSidebar,
  TbLayout,
  TbLeaf,
  TbLego,
  TbLemon2,
  TbLemon,
  TbLetterA,
  TbLetterB,
  TbLetterC,
  TbLetterCaseLower,
  TbLetterCaseToggle,
  TbLetterCaseUpper,
  TbLetterCase,
  TbLetterD,
  TbLetterE,
  TbLetterF,
  TbLetterG,
  TbLetterH,
  TbLetterI,
  TbLetterJ,
  TbLetterK,
  TbLetterL,
  TbLetterM,
  TbLetterN,
  TbLetterO,
  TbLetterP,
  TbLetterQ,
  TbLetterR,
  TbLetterS,
  TbLetterSpacing,
  TbLetterT,
  TbLetterU,
  TbLetterV,
  TbLetterW,
  TbLetterX,
  TbLetterY,
  TbLetterZ,
  TbLicense,
  TbLifebuoy,
  TbLineDashed,
  TbLineDotted,
  TbLineHeight,
  TbLine,
  TbLink,
  TbListCheck,
  TbListDetails,
  TbListNumbers,
  TbListSearch,
  TbList,
  TbLivePhoto,
  TbLiveView,
  TbLoader2,
  TbLoaderQuarter,
  TbLoader,
  TbLocation,
  TbLockAccess,
  TbLockOpen,
  TbLockSquare,
  TbLock,
  TbLogicAnd,
  TbLogicBuffer,
  TbLogicNand,
  TbLogicNor,
  TbLogicNot,
  TbLogicOr,
  TbLogicXnor,
  TbLogicXor,
  TbLogin,
  TbLogout,
  TbLollipop,
  TbLuggage,
  TbLungs,
  TbMacro,
  TbMagnet,
  TbMailFast,
  TbMailForward,
  TbMailOpened,
  TbMail,
  TbMailbox,
  TbMan,
  TbManualGearbox,
  TbMap2,
  TbMapPin,
  TbMapPins,
  TbMapSearch,
  TbMap,
  TbMarkdown,
  TbMarquee2,
  TbMarquee,
  TbMars,
  TbMask,
  TbMasksTheater,
  TbMassage,
  TbMathAvg,
  TbMathFunction,
  TbMathMax,
  TbMathMin,
  TbMathSymbols,
  TbMath,
  TbMaximize,
  TbMeat,
  TbMedal2,
  TbMedal,
  TbMedicalCross,
  TbMedicineSyrup,
  TbMenu2,
  TbMenu,
  TbMessage2Code,
  TbMessage2Share,
  TbMessage2,
  TbMessageCircle2,
  TbMessageCircle,
  TbMessageCode,
  TbMessageDots,
  TbMessageForward,
  TbMessageLanguage,
  TbMessagePlus,
  TbMessageReport,
  TbMessageShare,
  TbMessage,
  TbMessages,
  TbMeteor,
  TbMicrophone2,
  TbMicrophone,
  TbMicroscope,
  TbMicrowave,
  TbMilitaryAward,
  TbMilitaryRank,
  TbMilk,
  TbMinimize,
  TbMinusVertical,
  TbMinus,
  TbMist,
  TbMoodBoy,
  TbMoodConfuzed,
  TbMoodCrazyHappy,
  TbMoodCry,
  TbMoodEmpty,
  TbMoodHappy,
  TbMoodKid,
  TbMoodNervous,
  TbMoodNeutral,
  TbMoodSad,
  TbMoodSmile,
  TbMoodSuprised,
  TbMoodTongue,
  TbMoon2,
  TbMoonStars,
  TbMoon,
  TbMoped,
  TbMotorbike,
  TbMountain,
  TbMouse2,
  TbMouse,
  TbMovie,
  TbMug,
  TbMultiplier05x,
  TbMultiplier15x,
  TbMultiplier1x,
  TbMultiplier2x,
  TbMushroom,
  TbMusic,
  TbNetwork,
  TbNewSection,
  TbNews,
  TbNfc,
  TbNoCopyright,
  TbNoCreativeCommons,
  TbNoDerivatives,
  TbNorthStar,
  TbNote,
  TbNotebook,
  TbNotes,
  TbNotification,
  TbNumber0,
  TbNumber1,
  TbNumber2,
  TbNumber3,
  TbNumber4,
  TbNumber5,
  TbNumber6,
  TbNumber7,
  TbNumber8,
  TbNumber9,
  TbNumber,
  TbNumbers,
  TbNurse,
  TbOctagon,
  TbOld,
  TbOlympics,
  TbOmega,
  TbOutbound,
  TbOutlet,
  TbOvalVertical,
  TbOval,
  TbOverline,
  TbPackage,
  TbPackageExport,
  TbPackageImport,
  TbPacman,
  TbPageBreak,
  TbPaint,
  TbPalette,
  TbPanoramaHorizontal,
  TbPanoramaVertical,
  TbPaperBag,
  TbPaperclip,
  TbParachute,
  TbParentheses,
  TbParking,
  TbPaw,
  TbPeace,
  TbPencilMinus,
  TbPencilPlus,
  TbPencil,
  TbPennant2,
  TbPennant,
  TbPentagon,
  TbPepper,
  TbPercentage,
  TbPerspective,
  TbPhoneCall,
  TbPhoneCalling,
  TbPhoneCheck,
  TbPhoneIncoming,
  TbPhoneOutgoing,
  TbPhonePause,
  TbPhonePlus,
  TbPhoneX,
  TbPhone,
  TbPhoto,
  TbPhysotherapist,
  TbPictureInPictureOn,
  TbPictureInPictureTop,
  TbPictureInPicture,
  TbPig,
  TbPill,
  TbPills,
  TbPin,
  TbPinned,
  TbPizza,
  TbPlaneArrival,
  TbPlaneDeparture,
  TbPlaneInflight,
  TbPlaneTilt,
  TbPlane,
  TbPlanet,
  TbPlant2,
  TbPlant,
  TbPlayCard,
  TbPlayerEject,
  TbPlayerPause,
  TbPlayerPlay,
  TbPlayerRecord,
  TbPlayerSkipBack,
  TbPlayerSkipForward,
  TbPlayerStop,
  TbPlayerTrackNext,
  TbPlayerTrackPrev,
  TbPlaylistAdd,
  TbPlaylistX,
  TbPlaylist,
  TbPlugConnectedX,
  TbPlugConnected,
  TbPlugX,
  TbPlug,
  TbPlus,
  TbPodium,
  TbPoint,
  TbPointer,
  TbPokeball,
  TbPolaroid,
  TbPolygon,
  TbPoo,
  TbPool,
  TbPower,
  TbPray,
  TbPremiumRights,
  TbPrescription,
  TbPresentationAnalytics,
  TbPresentation,
  TbPrinter,
  TbPrison,
  TbPrompt,
  TbPropeller,
  TbPuzzle2,
  TbPuzzle,
  TbPyramid,
  TbQrcode,
  TbQuestionMark,
  TbQuote,
  TbRadar2,
  TbRadar,
  TbRadio,
  TbRadioactive,
  TbRadiusBottomLeft,
  TbRadiusBottomRight,
  TbRadiusTopLeft,
  TbRadiusTopRight,
  TbRainbow,
  TbRating12Plus,
  TbRating14Plus,
  TbRating16Plus,
  TbRating18Plus,
  TbRating21Plus,
  TbReceipt2,
  TbReceiptRefund,
  TbReceiptTax,
  TbReceipt,
  TbRecharging,
  TbRecordMail,
  TbRectangleVertical,
  TbRectangle,
  TbRecycle,
  TbRefreshAlert,
  TbRefreshDot,
  TbRefresh,
  TbRegistered,
  TbRelationManyToMany,
  TbRelationOneToMany,
  TbRelationOneToOne,
  TbRepeatOnce,
  TbRepeat,
  TbReplace,
  TbReportAnalytics,
  TbReportMedical,
  TbReportMoney,
  TbReportSearch,
  TbReport,
  TbResize,
  TbRipple,
  TbRoadSign,
  TbRoad,
  TbRobot,
  TbRocket,
  TbRollerSkating,
  TbRollercoaster,
  TbRotate2,
  TbRotate360,
  TbRotateClockwise2,
  TbRotateClockwise,
  TbRotateDot,
  TbRotateRectangle,
  TbRotate,
  TbRoute,
  TbRouter,
  TbRowInsertBottom,
  TbRowInsertTop,
  TbRss,
  TbRuler2,
  TbRuler3,
  TbRulerMeasure,
  TbRuler,
  TbRun,
  TbSailboat,
  TbSalt,
  TbSatellite,
  TbSausage,
  TbScaleOutline,
  TbScale,
  TbScanEye,
  TbScan,
  TbSchema,
  TbSchool,
  TbScissors,
  TbScooterElectric,
  TbScooter,
  TbScreenShare,
  TbScreenshot,
  TbScribble,
  TbScubaMask,
  TbSearch,
  TbSectionSign,
  TbSection,
  TbSeeding,
  TbSelect,
  TbSelector,
  TbSend,
  TbSeo,
  TbSeparatorHorizontal,
  TbSeparatorVertical,
  TbSeparator,
  TbServer2,
  TbServer,
  TbServicemark,
  TbSettingsAutomation,
  TbSettings,
  TbShadow,
  TbShape2,
  TbShape3,
  TbShape,
  TbShare,
  TbShieldCheck,
  TbShieldCheckered,
  TbShieldChevron,
  TbShieldLock,
  TbShieldX,
  TbShield,
  TbShip,
  TbShirtSport,
  TbShirt,
  TbShoe,
  TbShoppingCartDiscount,
  TbShoppingCartPlus,
  TbShoppingCartX,
  TbShoppingCart,
  TbShovel,
  TbShredder,
  TbSignLeft,
  TbSignRight,
  TbSignal3g,
  TbSignal4gPlus,
  TbSignal4g,
  TbSignal5g,
  TbSignature,
  TbSitemap,
  TbSkateboard,
  TbSkull,
  TbSleigh,
  TbSlice,
  TbSlideshow,
  TbSmartHome,
  TbSmokingNo,
  TbSmoking,
  TbSnowflake,
  TbSnowman,
  TbSoccerField,
  TbSocial,
  TbSock,
  TbSofa,
  TbSortAscending2,
  TbSortAscendingLetters,
  TbSortAscendingNumbers,
  TbSortAscending,
  TbSortDescending2,
  TbSortDescendingLetters,
  TbSortDescendingNumbers,
  TbSortDescending,
  TbSos,
  TbSoup,
  TbSpace,
  TbSpacingHorizontal,
  TbSpacingVertical,
  TbSpade,
  TbSpeakerphone,
  TbSpeedboat,
  TbSpider,
  TbSpiral,
  TbSportBillard,
  TbSpy,
  TbSquareF0,
  TbSquareF1,
  TbSquareF2,
  TbSquareF3,
  TbSquareF4,
  TbSquareF5,
  TbSquareF6,
  TbSquareF7,
  TbSquareF8,
  TbSquareF9,
  TbSquareAsterisk,
  TbSquareCheck,
  TbSquareDot,
  TbSquareForbid2,
  TbSquareForbid,
  TbSquareHalf,
  TbSquareMinus,
  TbSquarePlus,
  TbSquareRoot2,
  TbSquareRoot,
  TbSquareRotatedForbid2,
  TbSquareRotatedForbid,
  TbSquareRotated,
  TbSquareToggleHorizontal,
  TbSquareToggle,
  TbSquareX,
  TbSquare,
  TbSquaresDiagonal,
  TbSquaresFilled,
  TbStack2,
  TbStack3,
  TbStackPop,
  TbStackPush,
  TbStack,
  TbStairsDown,
  TbStairsUp,
  TbStairs,
  TbStarHalf,
  TbStar,
  TbStars,
  TbSteam,
  TbSteeringWheel,
  TbStepInto,
  TbStepOut,
  TbStethoscope,
  TbSticker,
  TbStorm,
  TbStrikethrough,
  TbSubmarine,
  TbSubscript,
  TbSubtask,
  TbSum,
  TbSunHigh,
  TbSunLow,
  TbSunWind,
  TbSun,
  TbSunglasses,
  TbSunrise,
  TbSunset2,
  TbSunset,
  TbSuperscript,
  TbSvg,
  TbSwimming,
  TbSwitch2,
  TbSwitch3,
  TbSwitchHorizontal,
  TbSwitchVertical,
  TbSwitch,
  TbSword,
  TbSwords,
  TbTableAlias,
  TbTableExport,
  TbTableImport,
  TbTableOptions,
  TbTableShortcut,
  TbTable,
  TbTag,
  TbTags,
  TbTallymark1,
  TbTallymark2,
  TbTallymark3,
  TbTallymark4,
  TbTallymarks,
  TbTank,
  TbTarget,
  TbTelescope,
  TbTemperatureCelsius,
  TbTemperatureFahrenheit,
  TbTemperatureMinus,
  TbTemperaturePlus,
  TbTemperature,
  TbTemplate,
  TbTent,
  TbTerminal2,
  TbTerminal,
  TbTestPipe2,
  TbTestPipe,
  TbTextDecrease,
  TbTextDirectionLtr,
  TbTextDirectionRtl,
  TbTextIncrease,
  TbTextRecognition,
  TbTextResize,
  TbTextWrapDisabled,
  TbTextWrap,
  TbThermometer,
  TbThumbDown,
  TbThumbUp,
  TbTicket,
  TbTie,
  TbTiltShift,
  TbTimeline,
  TbTir,
  TbToggleLeft,
  TbToggleRight,
  TbToiletPaper,
  TbTool,
  TbToolsKitchen2,
  TbToolsKitchen,
  TbTools,
  TbTornado,
  TbTournament,
  TbTrack,
  TbTractor,
  TbTrademark,
  TbTrafficCone,
  TbTrafficLights,
  TbTrain,
  TbTransferIn,
  TbTransferOut,
  TbTrashX,
  TbTrash,
  TbTree,
  TbTrees,
  TbTrendingDown2,
  TbTrendingDown3,
  TbTrendingDown,
  TbTrendingUp2,
  TbTrendingUp3,
  TbTrendingUp,
  TbTriangleInverted,
  TbTriangleSquareCircle,
  TbTriangle,
  TbTriangles,
  TbTrident,
  TbTrophy,
  TbTruckDelivery,
  TbTruckLoading,
  TbTruckReturn,
  TbTruck,
  TbTypography,
  TbUfo,
  TbUmbrella,
  TbUnderline,
  TbUnlink,
  TbUpload,
  TbUrgent,
  TbUsb,
  TbUserCheck,
  TbUserCircle,
  TbUserExclamation,
  TbUserMinus,
  TbUserPlus,
  TbUserSearch,
  TbUserX,
  TbUser,
  TbUsers,
  TbVaccineBottle,
  TbVaccine,
  TbVariable,
  TbVectorBezier2,
  TbVectorBezier,
  TbVectorTriangle,
  TbVector,
  TbVenus,
  TbVersions,
  TbVideoMinus,
  TbVideoPlus,
  TbVideo,
  TbView360,
  TbViewfinder,
  TbViewportNarrow,
  TbViewportWide,
  TbVinyl,
  TbVirusSearch,
  TbVirus,
  TbVocabulary,
  TbVolume2,
  TbVolume3,
  TbVolume,
  TbWalk,
  TbWall,
  TbWallet,
  TbWallpaper,
  TbWand,
  TbWashMachine,
  TbWaveSawTool,
  TbWaveSine,
  TbWaveSquare,
  TbWebhook,
  TbWheelchair,
  TbWifi0,
  TbWifi1,
  TbWifi2,
  TbWifi,
  TbWind,
  TbWindmill,
  TbWindowMaximize,
  TbWindowMinimize,
  TbWindow,
  TbWindsock,
  TbWiperWash,
  TbWiper,
  TbWoman,
  TbWorldDownload,
  TbWorldLatitude,
  TbWorldLongitude,
  TbWorldUpload,
  TbWorld,
  TbWreckingBall,
  TbWritingSign,
  TbWriting,
  TbX,
  TbYinYang,
  TbYoga,
  TbZeppelin,
  TbZodiacAquarius,
  TbZodiacAries,
  TbZodiacCancer,
  TbZodiacCapricorn,
  TbZodiacGemini,
  TbZodiacLeo,
  TbZodiacLibra,
  TbZodiacPisces,
  TbZodiacSagittarius,
  TbZodiacScorpio,
  TbZodiacTaurus,
  TbZodiacVirgo,
  TbZoomCancel,
  TbZoomCheck,
  TbZoomCode,
  TbZoomExclamation,
  TbZoomInArea,
  TbZoomIn,
  TbZoomMoney,
  TbZoomOutArea,
  TbZoomOut,
  TbZoomPan,
  TbZoomQuestion,
  TbZoomReset,
  TbZzz,
  TbCode
} from "solid-icons/tb"
import { Component } from "solid-js"

export const namedIcons: { [key: string]: Component<IconProps> | undefined } = {
  "3dCubeSphere": Tb3dCubeSphere,
  "3dRotate": Tb3dRotate,
  Abacus: TbAbacus,
  AccessPoint: TbAccessPoint,
  Accessible: TbAccessible,
  ActivityHeartbeat: TbActivityHeartbeat,
  Activity: TbActivity,
  Ad2: TbAd2,
  Ad: TbAd,
  AddressBook: TbAddressBook,
  Adjustments: TbAdjustments,
  AerialLift: TbAerialLift,
  Affiliate: TbAffiliate,
  Alarm: TbAlarm,
  Album: TbAlbum,
  AlertCircle: TbAlertCircle,
  AlertOctagon: TbAlertOctagon,
  AlertTriangle: TbAlertTriangle,
  Alien: TbAlien,
  AlignLeft: TbAlignLeft,
  AlphabetCyrillic: TbAlphabetCyrillic,
  AlphabetGreek: TbAlphabetGreek,
  AlphabetLatin: TbAlphabetLatin,
  Ambulance: TbAmbulance,
  Ampersand: TbAmpersand,
  Anchor: TbAnchor,
  Angle: TbAngle,
  Ankh: TbAnkh,
  AntennaBars3: TbAntennaBars3,
  Antenna: TbAntenna,
  Aperture: TbAperture,
  ApiApp: TbApiApp,
  Api: TbApi,
  AppWindow: TbAppWindow,
  Apple: TbApple,
  Apps: TbApps,
  Archive: TbArchive,
  Armchair2: TbArmchair2,
  Armchair: TbArmchair,
  ArrowsCross: TbArrowsCross,
  ArrowsDiagonal2: TbArrowsDiagonal2,
  ArrowsDiagonalMinimize2: TbArrowsDiagonalMinimize2,
  ArrowsDiagonalMinimize: TbArrowsDiagonalMinimize,
  ArrowsDiagonal: TbArrowsDiagonal,
  ArrowsDoubleNeSw: TbArrowsDoubleNeSw,
  ArrowsDoubleNwSe: TbArrowsDoubleNwSe,
  ArrowsDoubleSeNw: TbArrowsDoubleSeNw,
  ArrowsDoubleSwNe: TbArrowsDoubleSwNe,
  ArrowsDownUp: TbArrowsDownUp,
  ArrowsDown: TbArrowsDown,
  ArrowsExchange2: TbArrowsExchange2,
  ArrowsExchange: TbArrowsExchange,
  ArrowsHorizontal: TbArrowsHorizontal,
  ArrowsJoin2: TbArrowsJoin2,
  ArrowsJoin: TbArrowsJoin,
  ArrowsLeftDown: TbArrowsLeftDown,
  ArrowsLeftRight: TbArrowsLeftRight,
  ArrowsLeft: TbArrowsLeft,
  ArrowsMaximize: TbArrowsMaximize,
  ArrowsMinimize: TbArrowsMinimize,
  ArrowsMoveHorizontal: TbArrowsMoveHorizontal,
  ArrowsMoveVertical: TbArrowsMoveVertical,
  ArrowsMove: TbArrowsMove,
  ArrowsRandom: TbArrowsRandom,
  ArrowsRightDown: TbArrowsRightDown,
  ArrowsRightLeft: TbArrowsRightLeft,
  ArrowsRight: TbArrowsRight,
  ArrowsShuffle2: TbArrowsShuffle2,
  ArrowsShuffle: TbArrowsShuffle,
  ArrowsSort: TbArrowsSort,
  ArrowsSplit2: TbArrowsSplit2,
  ArrowsSplit: TbArrowsSplit,
  ArrowsUpDown: TbArrowsUpDown,
  ArrowsUpLeft: TbArrowsUpLeft,
  ArrowsUpRight: TbArrowsUpRight,
  ArrowsUp: TbArrowsUp,
  ArrowsVertical: TbArrowsVertical,
  Artboard: TbArtboard,
  Article: TbArticle,
  AspectRatio: TbAspectRatio,
  Assembly: TbAssembly,
  Asset: TbAsset,
  AsteriskSimple: TbAsteriskSimple,
  Asterisk: TbAsterisk,
  At: TbAt,
  Atom2: TbAtom2,
  Atom: TbAtom,
  AugmentedReality: TbAugmentedReality,
  Award: TbAward,
  Axe: TbAxe,
  AxisX: TbAxisX,
  AxisY: TbAxisY,
  BabyCarriage: TbBabyCarriage,
  Backhoe: TbBackhoe,
  Backpack: TbBackpack,
  Backspace: TbBackspace,
  Badge: TbBadge,
  Badges: TbBadges,
  BallAmericanFootball: TbBallAmericanFootball,
  BallBaseball: TbBallBaseball,
  BallBasketball: TbBallBasketball,
  BallBowling: TbBallBowling,
  BallFootball: TbBallFootball,
  BallTennis: TbBallTennis,
  BallVolleyball: TbBallVolleyball,
  Ballon: TbBalloon,
  Ballpen: TbBallpen,
  Ban: TbBan,
  Bandage: TbBandage,
  Barbell: TbBarbell,
  Barcode: TbBarcode,
  Barrel: TbBarrel,
  BarrierBlock: TbBarrierBlock,
  Baseline: TbBaseline,
  Basket: TbBasket,
  Bat: TbBat,
  Bath: TbBath,
  Battery4: TbBattery4,
  BatteryAutomotive: TbBatteryAutomotive,
  BatteryCharging: TbBatteryCharging,
  BatteryEco: TbBatteryEco,
  Battery: TbBattery,
  Beach: TbBeach,
  Bed: TbBed,
  Beer: TbBeer,
  BellMinus: TbBellMinus,
  BellPlus: TbBellPlus,
  BellRinging2: TbBellRinging2,
  BellRinging: TbBellRinging,
  BellSchool: TbBellSchool,
  BellX: TbBellX,
  BellZ: TbBellZ,
  Bell: TbBell,
  Bible: TbBible,
  Bike: TbBike,
  Binary: TbBinary,
  Biohazard: TbBiohazard,
  Blockquote: TbBlockquote,
  BluetoothConnected: TbBluetoothConnected,
  BluetoothX: TbBluetoothX,
  Bluetooth: TbBluetooth,
  Blur: TbBlur,
  Bold: TbBold,
  Bolt: TbBolt,
  Bone: TbBone,
  Book2: TbBook2,
  BookDownload: TbBookDownload,
  BookUpload: TbBookUpload,
  Book: TbBook,
  Bookmark: TbBookmark,
  Bookmarks: TbBookmarks,
  Books: TbBooks,
  BorderTop: TbBorderTop,
  BorderVertical: TbBorderVertical,
  Bottle: TbBottle,
  Bow: TbBow,
  BoxMargin: TbBoxMargin,
  BoxModel2: TbBoxModel2,
  BoxModel: TbBoxModel,
  BoxMultiple: TbBoxMultiple,
  BoxPadding: TbBoxPadding,
  Box: TbBox,
  Braces: TbBraces,
  BracketsContainEnd: TbBracketsContainEnd,
  BracketsContainStart: TbBracketsContainStart,
  BracketsContain: TbBracketsContain,
  Brackets: TbBrackets,
  Bread: TbBread,
  Briefcase: TbBriefcase,
  Brightness2: TbBrightness2,
  BrightnessDown: TbBrightnessDown,
  BrightnessHalf: TbBrightnessHalf,
  BrightnessUp: TbBrightnessUp,
  Brightness: TbBrightness,
  Broadcast: TbBroadcast,
  BrowserCheck: TbBrowserCheck,
  BrowserPlus: TbBrowserPlus,
  BrowserX: TbBrowserX,
  Browser: TbBrowser,
  Brush: TbBrush,
  Bucket: TbBucket,
  Bug: TbBug,
  BuildingArch: TbBuildingArch,
  BuildingBank: TbBuildingBank,
  BuildingBridge2: TbBuildingBridge2,
  BuildingBridge: TbBuildingBridge,
  BuildingCarousel: TbBuildingCarousel,
  BuildingCastle: TbBuildingCastle,
  BuildingChurch: TbBuildingChurch,
  BuildingCommunity: TbBuildingCommunity,
  BuildingCottage: TbBuildingCottage,
  BuildingFactory2: TbBuildingFactory2,
  BuildingFactory: TbBuildingFactory,
  BuildingFortress: TbBuildingFortress,
  BuildingHospital: TbBuildingHospital,
  BuildingLighthouse: TbBuildingLighthouse,
  BuildingMonument: TbBuildingMonument,
  BuildingPavilon: TbBuildingPavilion,
  BuildingSkyscraper: TbBuildingSkyscraper,
  BuildingStore: TbBuildingStore,
  BuildingWarehouse: TbBuildingWarehouse,
  Building: TbBuilding,
  Bulb: TbBulb,
  Bulldozer: TbBulldozer,
  Bus: TbBus,
  Businessplan: TbBusinessplan,
  Butterfly: TbButterfly,
  CSharp: TbBrandCSharp,
  Cactus: TbCactus,
  Cake: TbCake,
  Calculator: TbCalculator,
  CalendarEvent: TbCalendarEvent,
  CalendarMinus: TbCalendarMinus,
  CalendarPlus: TbCalendarPlus,
  CalendarStats: TbCalendarStats,
  CalendarTime: TbCalendarTime,
  Calendar: TbCalendar,
  CameraMinus: TbCameraMinus,
  CameraPlus: TbCameraPlus,
  CameraRotate: TbCameraRotate,
  CameraSelfie: TbCameraSelfie,
  Camera: TbCamera,
  Candle: TbCandle,
  Candy: TbCandy,
  Capture: TbCapture,
  CarCrane: TbCarCrane,
  CarCrash: TbCarCrash,
  Car: TbCar,
  Caravan: TbCaravan,
  Cardboards: TbCardboards,
  CaretDown: TbCaretDown,
  CaretLeft: TbCaretLeft,
  CaretRight: TbCaretRight,
  CaretUp: TbCaretUp,
  Carrot: TbCarrot,
  CashBanknote: TbCashBanknote,
  Cash: TbCash,
  Cast: TbCast,
  Category2: TbCategory2,
  Category: TbCategory,
  Ce: TbCe,
  CellSignal1: TbCellSignal1,
  CellSignal2: TbCellSignal2,
  CellSignal3: TbCellSignal3,
  CellSignal4: TbCellSignal4,
  CellSignal5: TbCellSignal5,
  Cell: TbCell,
  Certificate2: TbCertificate2,
  Certificate: TbCertificate,
  ChargingPile: TbChargingPile,
  ChartArcs3: TbChartArcs3,
  ChartArcs: TbChartArcs,
  ChartAreaLine: TbChartAreaLine,
  ChartArea: TbChartArea,
  ChartArrowsVertical: TbChartArrowsVertical,
  ChartArrows: TbChartArrows,
  ChartBar: TbChartBar,
  ChartBubble: TbChartBubble,
  ChartCandle: TbChartCandle,
  ChartCircles: TbChartCircles,
  ChartDonut2: TbChartDonut2,
  ChartDonut3: TbChartDonut3,
  ChartDonut4: TbChartDonut4,
  ChartDonut: TbChartDonut,
  ChartDots2: TbChartDots2,
  ChartDots3: TbChartDots3,
  ChartDots: TbChartDots,
  ChartInfographic: TbChartInfographic,
  ChartLine: TbChartLine,
  ChartPie2: TbChartPie2,
  ChartPie3: TbChartPie3,
  ChartPie4: TbChartPie4,
  ChartPie: TbChartPie,
  ChartRadar: TbChartRadar,
  Check: TbCheck,
  Checkbox: TbCheckbox,
  Checklist: TbChecklist,
  Checks: TbChecks,
  CheckupList: TbCheckupList,
  Cheese: TbCheese,
  ChefHat: TbChefHat,
  ChevronDownLeft: TbChevronDownLeft,
  ChevronDownRight: TbChevronDownRight,
  ChevronDown: TbChevronDown,
  ChevronLeft: TbChevronLeft,
  ChevronRight: TbChevronRight,
  ChevronUpLeft: TbChevronUpLeft,
  ChevronUpRight: TbChevronUpRight,
  ChevronUp: TbChevronUp,
  ChevronsDownLeft: TbChevronsDownLeft,
  ChevronsDownRight: TbChevronsDownRight,
  ChevronsDown: TbChevronsDown,
  ChevronsLeft: TbChevronsLeft,
  ChevronsRight: TbChevronsRight,
  ChevronsUpLeft: TbChevronsUpLeft,
  ChevronsUpRight: TbChevronsUpRight,
  ChevronsUp: TbChevronsUp,
  ChristmasTree: TbChristmasTree,
  Circle0: TbCircleNumber0,
  Circle1: TbCircleNumber1,
  Circle2: TbCircleNumber2,
  Circle3: TbCircleNumber3,
  Circle4: TbCircleNumber4,
  Circle5: TbCircleNumber5,
  Circle6: TbCircleNumber6,
  Circle7: TbCircleNumber7,
  Circle8: TbCircleNumber8,
  Circle9: TbCircleNumber9,
  CircleCheck: TbCircleCheck,
  CircleDashed: TbCircleDashed,
  CircleDot: TbCircleDot,
  CircleDotted: TbCircleDotted,
  CircleHalf2: TbCircleHalf2,
  CircleHalfVertical: TbCircleHalfVertical,
  CircleHalf: TbCircleHalf,
  CircleMinus: TbCircleMinus,
  CirclePlus: TbCirclePlus,
  CircleRectangle: TbCircleRectangle,
  CircleSquare: TbCircleSquare,
  CircleTriangle: TbCircleTriangle,
  CircleX: TbCircleX,
  Circle: TbCircle,
  Circles: TbCircles,
  CircuitAmmeter: TbCircuitAmmeter,
  CircuitBattery: TbCircuitBattery,
  CircuitBulb: TbCircuitBulb,
  CircuitCapacitorPolarized: TbCircuitCapacitorPolarized,
  CircuitCapacitor: TbCircuitCapacitor,
  CircuitCellPlus: TbCircuitCellPlus,
  CircuitCell: TbCircuitCell,
  CircuitChangeover: TbCircuitChangeover,
  CircuitDiodeZener: TbCircuitDiodeZener,
  CircuitDiode: TbCircuitDiode,
  CircuitGroundDigital: TbCircuitGroundDigital,
  CircuitGround: TbCircuitGround,
  CircuitInductor: TbCircuitInductor,
  CircuitMotor: TbCircuitMotor,
  CircuitPushbutton: TbCircuitPushbutton,
  CircuitResistor: TbCircuitResistor,
  CircuitSwitchClosed: TbCircuitSwitchClosed,
  CircuitSwitchOpen: TbCircuitSwitchOpen,
  CircuitVoltmeter: TbCircuitVoltmeter,
  ClearAll: TbClearAll,
  ClearFormatting: TbClearFormatting,
  Click: TbClick,
  ClipboardCheck: TbClipboardCheck,
  ClipboardList: TbClipboardList,
  ClipboardPlus: TbClipboardPlus,
  ClipboardText: TbClipboardText,
  ClipboardX: TbClipboardX,
  Clipboard: TbClipboard,
  Clock2: TbClock2,
  Clock: TbClock,
  ClothesRack: TbClothesRack,
  CloudComputing: TbCloudComputing,
  CloudDataConnection: TbCloudDataConnection,
  CloudDownload: TbCloudDownload,
  CloudFog: TbCloudFog,
  CloudLockOpen: TbCloudLockOpen,
  CloudLock: TbCloudLock,
  CloudRain: TbCloudRain,
  CloudSnow: TbCloudSnow,
  CloudStorm: TbCloudStorm,
  CloudUpload: TbCloudUpload,
  Cloud: TbCloud,
  Clover2: TbClover2,
  Clover: TbClover,
  Clubs: TbClubs,
  CodeMinus: TbCodeMinus,
  CodePlus: TbCodePlus,
  Code: TbCode,
  Coin: TbCoin,
  ColorPicker: TbColorPicker,
  ColorSwatch: TbColorSwatch,
  ColumnInsertLeft: TbColumnInsertLeft,
  ColumnInsertRight: TbColumnInsertRight,
  Columns: TbColumns,
  Comet: TbComet,
  Command: TbCommand,
  Compass: TbCompass,
  Components: TbComponents,
  Cone2: TbCone2,
  Cone: TbCone,
  Confetti: TbConfetti,
  Container: TbContainer,
  Contrast2: TbContrast2,
  Contrast: TbContrast,
  Cookie: TbCookie,
  Copy: TbCopy,
  Copyleft: TbCopyleft,
  Copyright: TbCopyright,
  CornerDownLeftDouble: TbCornerDownLeftDouble,
  CornerDownLeft: TbCornerDownLeft,
  CornerDownRightDouble: TbCornerDownRightDouble,
  CornerDownRight: TbCornerDownRight,
  CornerLeftDownDouble: TbCornerLeftDownDouble,
  CornerLeftDown: TbCornerLeftDown,
  CornerLeftUpDouble: TbCornerLeftUpDouble,
  CornerLeftUp: TbCornerLeftUp,
  CornerRightDownDouble: TbCornerRightDownDouble,
  CornerRightDown: TbCornerRightDown,
  CornerRightUpDouble: TbCornerRightUpDouble,
  CornerRightUp: TbCornerRightUp,
  CornerUpLeftDouble: TbCornerUpLeftDouble,
  CornerUpLeft: TbCornerUpLeft,
  CornerUpRightDouble: TbCornerUpRightDouble,
  CornerUpRight: TbCornerUpRight,
  Cpu2: TbCpu2,
  Cpu: TbCpu,
  Crane: TbCrane,
  CreativeCommonsBy: TbCreativeCommonsBy,
  CreativeCommonsNc: TbCreativeCommonsNc,
  CreativeCommonsNd: TbCreativeCommonsNd,
  CreativeCommonsSa: TbCreativeCommonsSa,
  CreativeCommonsZero: TbCreativeCommonsZero,
  CreativeCommons: TbCreativeCommons,
  CreditCard: TbCreditCard,
  Cricket: TbCricket,
  Crop: TbCrop,
  Cross: TbCross,
  Crosshair: TbCrosshair,
  Crown: TbCrown,
  Crutches: TbCrutches,
  Cup: TbCup,
  Curling: TbCurling,
  CurlyLoop: TbCurlyLoop,
  CurrencyBahraini: TbCurrencyBahraini,
  CurrencyBaht: TbCurrencyBaht,
  CurrencyBitcoin: TbCurrencyBitcoin,
  CurrencyCent: TbCurrencyCent,
  CurrencyDinar: TbCurrencyDinar,
  CurrencyDirham: TbCurrencyDirham,
  CurrencyDogecoin: TbCurrencyDogecoin,
  CurrencyDollarAustralian: TbCurrencyDollarAustralian,
  CurrencyDollarCanadian: TbCurrencyDollarCanadian,
  CurrencyDollarSingapore: TbCurrencyDollarSingapore,
  CurrencyDollar: TbCurrencyDollar,
  CurrencyEthereum: TbCurrencyEthereum,
  CurrencyEuro: TbCurrencyEuro,
  CurrencyForint: TbCurrencyForint,
  CurrencyFrank: TbCurrencyFrank,
  CurrencyKroneCzech: TbCurrencyKroneCzech,
  CurrencyKroneDanish: TbCurrencyKroneDanish,
  CurrencyKroneSwedish: TbCurrencyKroneSwedish,
  CurrencyLeu: TbCurrencyLeu,
  CurrencyLira: TbCurrencyLira,
  CurrencyLitecoin: TbCurrencyLitecoin,
  CurrencyNaira: TbCurrencyNaira,
  CurrencyPound: TbCurrencyPound,
  CurrencyReal: TbCurrencyReal,
  CurrencyRenminbi: TbCurrencyRenminbi,
  CurrencyRipple: TbCurrencyRipple,
  CurrencyRiyal: TbCurrencyRiyal,
  CurrencyRubel: TbCurrencyRubel,
  CurrencyRupee: TbCurrencyRupee,
  CurrencyShekel: TbCurrencyShekel,
  CurrencyTaka: TbCurrencyTaka,
  CurrencyTugrik: TbCurrencyTugrik,
  CurrencyWon: TbCurrencyWon,
  CurrencyYen: TbCurrencyYen,
  CurrencyZloty: TbCurrencyZloty,
  Currency: TbCurrency,
  CurrentLocation: TbCurrentLocation,
  CursorText: TbCursorText,
  Cut: TbCut,
  Dashboard: TbDashboard,
  DatabaseExport: TbDatabaseExport,
  DatabaseImport: TbDatabaseImport,
  Database: TbDatabase,
  DentalBroken: TbDentalBroken,
  Dental: TbDental,
  Details: TbDetails,
  DeviceAnalytics: TbDeviceAnalytics,
  DeviceAudioTape: TbDeviceAudioTape,
  DeviceCameraPhone: TbDeviceCameraPhone,
  DeviceCctv: TbDeviceCctv,
  DeviceComputerCamera: TbDeviceComputerCamera,
  DeviceDesktopAnalytics: TbDeviceDesktopAnalytics,
  DeviceDesktop: TbDeviceDesktop,
  DeviceFloppy: TbDeviceFloppy,
  DeviceGamepad2: TbDeviceGamepad2,
  DeviceGamepad: TbDeviceGamepad,
  DeviceHeartMonitor: TbDeviceHeartMonitor,
  DeviceLaptop: TbDeviceLaptop,
  DeviceMobileCharging: TbDeviceMobileCharging,
  DeviceMobileMessage: TbDeviceMobileMessage,
  DeviceMobileRotated: TbDeviceMobileRotated,
  DeviceMobileVibration: TbDeviceMobileVibration,
  DeviceMobile: TbDeviceMobile,
  DeviceNintendo: TbDeviceNintendo,
  DeviceSpeaker: TbDeviceSpeaker,
  DeviceTablet: TbDeviceTablet,
  DeviceTvOld: TbDeviceTvOld,
  DeviceTv: TbDeviceTv,
  DeviceWatchStats2: TbDeviceWatchStats2,
  DeviceWatchStats: TbDeviceWatchStats,
  DeviceWatch: TbDeviceWatch,
  Devices2: TbDevices2,
  DevicesPc: TbDevicesPc,
  Devices: TbDevices,
  Dialpad: TbDialpad,
  Diamond: TbDiamond,
  Diamonds: TbDiamonds,
  Dice1: TbDice1,
  Dice2: TbDice2,
  Dice3: TbDice3,
  Dice4: TbDice4,
  Dice5: TbDice5,
  Dice6: TbDice6,
  Dice: TbDice,
  Dimensions: TbDimensions,
  DirectionHorizontal: TbDirectionHorizontal,
  DirectionSign: TbDirectionSign,
  Direction: TbDirection,
  Directions: TbDirections,
  Disabled2: TbDisabled2,
  Disabled: TbDisabled,
  Disc: TbDisc,
  Discount2: TbDiscount2,
  DiscountCheck: TbDiscountCheck,
  Discount: TbDiscount,
  Divide: TbDivide,
  Dna2: TbDna2,
  Dna: TbDna,
  DogBowl: TbDogBowl,
  DoorEnter: TbDoorEnter,
  DoorExit: TbDoorExit,
  Door: TbDoor,
  DotsCircleHorizontal: TbDotsCircleHorizontal,
  DotsDiagonal2: TbDotsDiagonal2,
  DotsDiagonal: TbDotsDiagonal,
  DotsVertical: TbDotsVertical,
  Dots: TbDots,
  Download: TbDownload,
  DragDrop2: TbDragDrop2,
  DragDrop: TbDragDrop,
  Drone: TbDrone,
  DropCircle: TbDropCircle,
  DropletFilled2: TbDropletFilled2,
  DropletFilled: TbDropletFilled,
  DropletHalf2: TbDropletHalf2,
  DropletHalf: TbDropletHalf,
  Droplet: TbDroplet,
  Ear: TbEar,
  EditCircle: TbEditCircle,
  Edit: TbEdit,
  Egg: TbEgg,
  Elevator: TbElevator,
  EmergencyBed: TbEmergencyBed,
  Emphasis: TbEmphasis,
  Engine: TbEngine,
  EqualNot: TbEqualNot,
  Equal: TbEqual,
  Eraser: TbEraser,
  Error404: TbError404,
  Exchange: TbExchange,
  ExclamationMark: TbExclamationMark,
  Explicit: TbExplicit,
  Exposure: TbExposure,
  ExternalLink: TbExternalLink,
  EyeCheck: TbEyeCheck,
  EyeTable: TbEyeTable,
  Eye: TbEye,
  Eyeglass2: TbEyeglass2,
  Eyeglass: TbEyeglass,
  FaceIdError: TbFaceIdError,
  FaceId: TbFaceId,
  FaceMask: TbFaceMask,
  Fall: TbFall,
  Feather: TbFeather,
  Fence: TbFence,
  FidgetSpinner: TbFidgetSpinner,
  File3d: TbFile3d,
  FileAlert: TbFileAlert,
  FileAnalytics: TbFileAnalytics,
  FileArrowLeft: TbFileArrowLeft,
  FileArrowRight: TbFileArrowRight,
  FileBarcode: TbFileBarcode,
  FileCertificate: TbFileCertificate,
  FileChart: TbFileChart,
  FileCheck: TbFileCheck,
  FileCode2: TbFileCode2,
  FileCode: TbFileCode,
  FileDatabase: TbFileDatabase,
  FileDescription: TbFileDescription,
  FileDiff: TbFileDiff,
  FileDigit: TbFileDigit,
  FileDislike: TbFileDislike,
  FileDollar: TbFileDollar,
  FileDots: TbFileDots,
  FileDownload: TbFileDownload,
  FileEuro: TbFileEuro,
  FileExport: TbFileExport,
  FileHorizontal: TbFileHorizontal,
  FileImport: TbFileImport,
  FileInfo: TbFileInfo,
  FileInvoice: TbFileInvoice,
  FileLike: TbFileLike,
  FileMinus: TbFileMinus,
  FileMusic: TbFileMusic,
  FilePencil: TbFilePencil,
  FilePhone: TbFilePhone,
  FilePlus: TbFilePlus,
  FilePower: TbFilePower,
  FileReport: TbFileReport,
  FileRss: TbFileRss,
  FileScissors: TbFileScissors,
  FileSearch: TbFileSearch,
  FileSettings: TbFileSettings,
  FileShredder: TbFileShredder,
  FileSignal: TbFileSignal,
  FileSpreadsheet: TbFileSpreadsheet,
  FileStar: TbFileStar,
  FileSymlink: TbFileSymlink,
  FileText: TbFileText,
  FileTime: TbFileTime,
  FileTypography: TbFileTypography,
  FileUnknown: TbFileUnknown,
  FileUpload: TbFileUpload,
  FileVector: TbFileVector,
  FileX: TbFileX,
  FileZip: TbFileZip,
  File: TbFile,
  Files: TbFiles,
  Filter: TbFilter,
  Fingerprint: TbFingerprint,
  Firetruck: TbFiretruck,
  FirstAidKit: TbFirstAidKit,
  FishBone: TbFishBone,
  FishHook: TbFishHook,
  Fish: TbFish,
  Flag2: TbFlag2,
  Flag3: TbFlag3,
  Flag: TbFlag,
  Flame: TbFlame,
  Flare: TbFlare,
  Flask2: TbFlask2,
  Flask: TbFlask,
  FlipHorizontal: TbFlipHorizontal,
  FlipVertical: TbFlipVertical,
  FloatCenter: TbFloatCenter,
  FloatLeft: TbFloatLeft,
  FloatNone: TbFloatNone,
  FloatRight: TbFloatRight,
  Flower: TbFlower,
  Focus2: TbFocus2,
  FocusCentered: TbFocusCentered,
  Focus: TbFocus,
  FoldDown: TbFoldDown,
  FoldUp: TbFoldUp,
  Fold: TbFold,
  FolderMinus: TbFolderMinus,
  FolderPlus: TbFolderPlus,
  FolderX: TbFolderX,
  Folder: TbFolder,
  Folders: TbFolders,
  Forbid2: TbForbid2,
  Forbid: TbForbid,
  Forklift: TbForklift,
  Forms: TbForms,
  Fountain: TbFountain,
  Frame: TbFrame,
  FreeRights: TbFreeRights,
  Fridge: TbFridge,
  Friends: TbFriends,
  Function: TbFunction,
  GardenCart: TbGardenCart,
  GasStation: TbGasStation,
  Gauge: TbGauge,
  Gavel: TbGavel,
  GenderAgender: TbGenderAgender,
  GenderAndrogyne: TbGenderAndrogyne,
  GenderBigender: TbGenderBigender,
  GenderDemiboy: TbGenderDemiboy,
  GenderDemigirl: TbGenderDemigirl,
  GenderEpicene: TbGenderEpicene,
  GenderFemale: TbGenderFemale,
  GenderFemme: TbGenderFemme,
  GenderGenderfluid: TbGenderGenderfluid,
  GenderGenderless: TbGenderGenderless,
  GenderGenderqueer: TbGenderGenderqueer,
  GenderHermaphrodite: TbGenderHermaphrodite,
  GenderIntergender: TbGenderIntergender,
  GenderMale: TbGenderMale,
  GenderNeutrois: TbGenderNeutrois,
  GenderThird: TbGenderThird,
  GenderTransgender: TbGenderTransgender,
  GenderTrasvesti: TbGenderTrasvesti,
  Geometry: TbGeometry,
  Ghost: TbGhost,
  Gif: TbGif,
  Gift: TbGift,
  GitBranch: TbGitBranch,
  GitCommit: TbGitCommit,
  GitCompare: TbGitCompare,
  GitFork: TbGitFork,
  GitMerge: TbGitMerge,
  GitPullRequestClosed: TbGitPullRequestClosed,
  GitPullRequestDraft: TbGitPullRequestDraft,
  GitPullRequest: TbGitPullRequest,
  Gizmo: TbGizmo,
  GlassFull: TbGlassFull,
  Glass: TbGlass,
  Globe: TbGlobe,
  Golf: TbGolf,
  Gps: TbGps,
  Grain: TbGrain,
  Graph: TbGraph,
  GridDots: TbGridDots,
  GridPattern: TbGridPattern,
  Grill: TbGrill,
  GripHorizontal: TbGripHorizontal,
  GripVertical: TbGripVertical,
  Growth: TbGrowth,
  H1: TbH1,
  H2: TbH2,
  H3: TbH3,
  H4: TbH4,
  H5: TbH5,
  H6: TbH6,
  Hammer: TbHammer,
  HandClick: TbHandClick,
  HandFinger: TbHandFinger,
  HandGrab: TbHandGrab,
  HandLittleFinger: TbHandLittleFinger,
  HandMiddleFinger: TbHandMiddleFinger,
  HandMove: TbHandMove,
  HandRingFinger: TbHandRingFinger,
  HandRock: TbHandRock,
  HandStop: TbHandStop,
  HandThreeFingers: TbHandThreeFingers,
  HandTwoFingers: TbHandTwoFingers,
  Hanger2: TbHanger2,
  Hanger: TbHanger,
  Hash: TbHash,
  Haze: TbHaze,
  Heading: TbHeading,
  Headphones: TbHeadphones,
  Headset: TbHeadset,
  HealthRecognition: TbHealthRecognition,
  HeartBroken: TbHeartBroken,
  HeartHandshake: TbHeartHandshake,
  HeartMinus: TbHeartMinus,
  HeartPlus: TbHeartPlus,
  HeartRateMonitor: TbHeartRateMonitor,
  Heart: TbHeart,
  Heartbeat: TbHeartbeat,
  HelicopterLanding: TbHelicopterLanding,
  Helicopter: TbHelicopter,
  Helmet: TbHelmet,
  Help: TbHelp,
  Hexagon: TbHexagon,
  Hexagons: TbHexagons,
  Hierarchy2: TbHierarchy2,
  Hierarchy3: TbHierarchy3,
  Hierarchy: TbHierarchy,
  Highlight: TbHighlight,
  HistoryToggle: TbHistoryToggle,
  History: TbHistory,
  Home2: TbHome2,
  Home: TbHome,
  HorseToy: TbHorseToy,
  HotelService: TbHotelService,
  HourglassEmpty: TbHourglassEmpty,
  HourglassHigh: TbHourglassHigh,
  HourglassLow: TbHourglassLow,
  Hourglass: TbHourglass,
  IceCream2: TbIceCream2,
  IceCream: TbIceCream,
  IceSkating: TbIceSkating,
  Icons: TbIcons,
  IdBadge2: TbIdBadge2,
  IdBadge: TbIdBadge,
  Id: TbId,
  Inbox: TbInbox,
  IndentDecrease: TbIndentDecrease,
  IndentIncrease: TbIndentIncrease,
  Infinity: TbInfinity,
  InfoCircle: TbInfoCircle,
  InfoSquare: TbInfoSquare,
  Italic: TbItalic,
  JewishStar: TbJewishStar,
  JumpRope: TbJumpRope,
  Karate: TbKarate,
  Kayak: TbKayak,
  Kering: TbKering,
  Key: TbKey,
  KeyboardHide: TbKeyboardHide,
  KeyboardShow: TbKeyboardShow,
  Keyboard: TbKeyboard,
  Ladder: TbLadder,
  Lamp2: TbLamp2,
  Lamp: TbLamp,
  LanguageHiragana: TbLanguageHiragana,
  LanguageKatakana: TbLanguageKatakana,
  Language: TbLanguage,
  Lasso: TbLasso,
  LayersDifference: TbLayersDifference,
  LayersIntersect2: TbLayersIntersect2,
  LayersIntersect: TbLayersIntersect,
  LayersLinked: TbLayersLinked,
  LayersSubtract: TbLayersSubtract,
  LayersUnion: TbLayersUnion,
  Layout2: TbLayout2,
  LayoutAlignBottom: TbLayoutAlignBottom,
  LayoutAlignCenter: TbLayoutAlignCenter,
  LayoutAlignLeft: TbLayoutAlignLeft,
  LayoutAlignMiddle: TbLayoutAlignMiddle,
  LayoutAlignRight: TbLayoutAlignRight,
  LayoutAlignTop: TbLayoutAlignTop,
  LayoutBoardSplit: TbLayoutBoardSplit,
  LayoutBoard: TbLayoutBoard,
  LayoutBottombarCollapse: TbLayoutBottombarCollapse,
  LayoutBottombarExpand: TbLayoutBottombarExpand,
  LayoutBottombar: TbLayoutBottombar,
  LayoutCards: TbLayoutCards,
  LayoutColumns: TbLayoutColumns,
  LayoutDashboard: TbLayoutDashboard,
  LayoutDistributeHorizontal: TbLayoutDistributeHorizontal,
  LayoutDistributeVertical: TbLayoutDistributeVertical,
  LayoutGridAdd: TbLayoutGridAdd,
  LayoutGrid: TbLayoutGrid,
  LayoutKanban: TbLayoutKanban,
  LayoutList: TbLayoutList,
  LayoutNavbarCollapse: TbLayoutNavbarCollapse,
  LayoutNavbarExpand: TbLayoutNavbarExpand,
  LayoutNavbar: TbLayoutNavbar,
  LayoutRows: TbLayoutRows,
  LayoutSidebarLeftCollapse: TbLayoutSidebarLeftCollapse,
  LayoutSidebarLeftExpand: TbLayoutSidebarLeftExpand,
  LayoutSidebarRightCollapse: TbLayoutSidebarRightCollapse,
  LayoutSidebarRightExpand: TbLayoutSidebarRightExpand,
  LayoutSidebarRight: TbLayoutSidebarRight,
  LayoutSidebar: TbLayoutSidebar,
  Layout: TbLayout,
  Leaf: TbLeaf,
  Lego: TbLego,
  Lemon2: TbLemon2,
  Lemon: TbLemon,
  LetterA: TbLetterA,
  LetterB: TbLetterB,
  LetterC: TbLetterC,
  LetterCaseLower: TbLetterCaseLower,
  LetterCaseToggle: TbLetterCaseToggle,
  LetterCaseUpper: TbLetterCaseUpper,
  LetterCase: TbLetterCase,
  LetterD: TbLetterD,
  LetterE: TbLetterE,
  LetterF: TbLetterF,
  LetterG: TbLetterG,
  LetterH: TbLetterH,
  LetterI: TbLetterI,
  LetterJ: TbLetterJ,
  LetterK: TbLetterK,
  LetterL: TbLetterL,
  LetterM: TbLetterM,
  LetterN: TbLetterN,
  LetterO: TbLetterO,
  LetterP: TbLetterP,
  LetterQ: TbLetterQ,
  LetterR: TbLetterR,
  LetterS: TbLetterS,
  LetterSpacing: TbLetterSpacing,
  LetterT: TbLetterT,
  LetterU: TbLetterU,
  LetterV: TbLetterV,
  LetterW: TbLetterW,
  LetterX: TbLetterX,
  LetterY: TbLetterY,
  LetterZ: TbLetterZ,
  License: TbLicense,
  Lifebuoy: TbLifebuoy,
  LineDashed: TbLineDashed,
  LineDotted: TbLineDotted,
  LineHeight: TbLineHeight,
  Line: TbLine,
  Link: TbLink,
  ListCheck: TbListCheck,
  ListDetails: TbListDetails,
  ListNumbers: TbListNumbers,
  ListSearch: TbListSearch,
  List: TbList,
  LivePhoto: TbLivePhoto,
  LiveView: TbLiveView,
  Loader2: TbLoader2,
  LoaderQuarter: TbLoaderQuarter,
  Loader: TbLoader,
  Location: TbLocation,
  LockAccess: TbLockAccess,
  LockOpen: TbLockOpen,
  LockSquare: TbLockSquare,
  Lock: TbLock,
  LogicAnd: TbLogicAnd,
  LogicBuffer: TbLogicBuffer,
  LogicNand: TbLogicNand,
  LogicNor: TbLogicNor,
  LogicNot: TbLogicNot,
  LogicOr: TbLogicOr,
  LogicXnor: TbLogicXnor,
  LogicXor: TbLogicXor,
  Login: TbLogin,
  Logout: TbLogout,
  Lollipop: TbLollipop,
  Luggage: TbLuggage,
  Lungs: TbLungs,
  Macro: TbMacro,
  Magnet: TbMagnet,
  MailFast: TbMailFast,
  MailForward: TbMailForward,
  MailOpened: TbMailOpened,
  Mail: TbMail,
  Mailbox: TbMailbox,
  Man: TbMan,
  ManualGearbox: TbManualGearbox,
  Map2: TbMap2,
  MapPin: TbMapPin,
  MapPins: TbMapPins,
  MapSearch: TbMapSearch,
  Map: TbMap,
  Markdown: TbMarkdown,
  Marquee2: TbMarquee2,
  Marquee: TbMarquee,
  Mars: TbMars,
  Mask: TbMask,
  MasksTheater: TbMasksTheater,
  Massage: TbMassage,
  MathAvg: TbMathAvg,
  MathFunction: TbMathFunction,
  MathMax: TbMathMax,
  MathMin: TbMathMin,
  MathSymbols: TbMathSymbols,
  Math: TbMath,
  Maximize: TbMaximize,
  Meat: TbMeat,
  Medal2: TbMedal2,
  Medal: TbMedal,
  MedicalCross: TbMedicalCross,
  MedicineSyrup: TbMedicineSyrup,
  Menu2: TbMenu2,
  Menu: TbMenu,
  Message2Code: TbMessage2Code,
  Message2Share: TbMessage2Share,
  Message2: TbMessage2,
  MessageCircle2: TbMessageCircle2,
  MessageCircle: TbMessageCircle,
  MessageCode: TbMessageCode,
  MessageDots: TbMessageDots,
  MessageForward: TbMessageForward,
  MessageLanguage: TbMessageLanguage,
  MessagePlus: TbMessagePlus,
  MessageReport: TbMessageReport,
  MessageShare: TbMessageShare,
  Message: TbMessage,
  Messages: TbMessages,
  Meteor: TbMeteor,
  Microphone2: TbMicrophone2,
  Microphone: TbMicrophone,
  Microscope: TbMicroscope,
  Microwave: TbMicrowave,
  MilitaryAward: TbMilitaryAward,
  MilitaryRank: TbMilitaryRank,
  Milk: TbMilk,
  Minimize: TbMinimize,
  MinusVertical: TbMinusVertical,
  Minus: TbMinus,
  Mist: TbMist,
  MoodBoy: TbMoodBoy,
  MoodConfuzed: TbMoodConfuzed,
  MoodCrazyHappy: TbMoodCrazyHappy,
  MoodCry: TbMoodCry,
  MoodEmpty: TbMoodEmpty,
  MoodHappy: TbMoodHappy,
  MoodKid: TbMoodKid,
  MoodNervous: TbMoodNervous,
  MoodNeutral: TbMoodNeutral,
  MoodSad: TbMoodSad,
  MoodSmile: TbMoodSmile,
  MoodSuprised: TbMoodSuprised,
  MoodTongue: TbMoodTongue,
  Moon2: TbMoon2,
  MoonStars: TbMoonStars,
  Moon: TbMoon,
  Moped: TbMoped,
  Motorbike: TbMotorbike,
  Mountain: TbMountain,
  Mouse2: TbMouse2,
  Mouse: TbMouse,
  Movie: TbMovie,
  Mug: TbMug,
  Multiplier05x: TbMultiplier05x,
  Multiplier15x: TbMultiplier15x,
  Multiplier1x: TbMultiplier1x,
  Multiplier2x: TbMultiplier2x,
  Mushroom: TbMushroom,
  Music: TbMusic,
  Network: TbNetwork,
  NewSection: TbNewSection,
  News: TbNews,
  Nfc: TbNfc,
  NoCopyright: TbNoCopyright,
  NoCreativeCommons: TbNoCreativeCommons,
  NoDerivatives: TbNoDerivatives,
  NorthStar: TbNorthStar,
  Note: TbNote,
  Notebook: TbNotebook,
  Notes: TbNotes,
  Notification: TbNotification,
  Number0: TbNumber0,
  Number1: TbNumber1,
  Number2: TbNumber2,
  Number3: TbNumber3,
  Number4: TbNumber4,
  Number5: TbNumber5,
  Number6: TbNumber6,
  Number7: TbNumber7,
  Number8: TbNumber8,
  Number9: TbNumber9,
  Number: TbNumber,
  Numbers: TbNumbers,
  Nurse: TbNurse,
  Octagon: TbOctagon,
  Old: TbOld,
  Olympics: TbOlympics,
  Omega: TbOmega,
  Outbound: TbOutbound,
  Outlet: TbOutlet,
  OvalVertical: TbOvalVertical,
  Oval: TbOval,
  Overline: TbOverline,
  Package: TbPackage,
  PackgeExport: TbPackageExport,
  PackgeImport: TbPackageImport,
  Pacman: TbPacman,
  PageBreak: TbPageBreak,
  Paint: TbPaint,
  Palette: TbPalette,
  PanoramaHorizontal: TbPanoramaHorizontal,
  PanoramaVertical: TbPanoramaVertical,
  PaperBag: TbPaperBag,
  Paperclip: TbPaperclip,
  Parachute: TbParachute,
  Parentheses: TbParentheses,
  Parking: TbParking,
  Paw: TbPaw,
  Peace: TbPeace,
  PencilMinus: TbPencilMinus,
  PencilPlus: TbPencilPlus,
  Pencil: TbPencil,
  Pennant2: TbPennant2,
  Pennant: TbPennant,
  Pentagon: TbPentagon,
  Pepper: TbPepper,
  Percentage: TbPercentage,
  Perspective: TbPerspective,
  PhoneCall: TbPhoneCall,
  PhoneCalling: TbPhoneCalling,
  PhoneCheck: TbPhoneCheck,
  PhoneIncoming: TbPhoneIncoming,
  PhoneOutgoing: TbPhoneOutgoing,
  PhonePause: TbPhonePause,
  PhonePlus: TbPhonePlus,
  PhoneX: TbPhoneX,
  Phone: TbPhone,
  Photo: TbPhoto,
  Physotherapist: TbPhysotherapist,
  PictureInPictureOn: TbPictureInPictureOn,
  PictureInPictureTop: TbPictureInPictureTop,
  PictureInPicture: TbPictureInPicture,
  Pig: TbPig,
  Pill: TbPill,
  Pills: TbPills,
  Pin: TbPin,
  Pinned: TbPinned,
  Pizza: TbPizza,
  PlaneArrival: TbPlaneArrival,
  PlaneDeparture: TbPlaneDeparture,
  PlaneInflight: TbPlaneInflight,
  PlaneTilt: TbPlaneTilt,
  Plane: TbPlane,
  Planet: TbPlanet,
  Plant2: TbPlant2,
  Plant: TbPlant,
  PlayCard: TbPlayCard,
  PlayerEject: TbPlayerEject,
  PlayerPause: TbPlayerPause,
  PlayerPlay: TbPlayerPlay,
  PlayerRecord: TbPlayerRecord,
  PlayerSkipBack: TbPlayerSkipBack,
  PlayerSkipForward: TbPlayerSkipForward,
  PlayerStop: TbPlayerStop,
  PlayerTrackNext: TbPlayerTrackNext,
  PlayerTrackPrev: TbPlayerTrackPrev,
  PlaylistAdd: TbPlaylistAdd,
  PlaylistX: TbPlaylistX,
  Playlist: TbPlaylist,
  PlugConnectedX: TbPlugConnectedX,
  PlugConnected: TbPlugConnected,
  PlugX: TbPlugX,
  Plug: TbPlug,
  Plus: TbPlus,
  Podium: TbPodium,
  Point: TbPoint,
  Pointer: TbPointer,
  Pokeball: TbPokeball,
  Polaroid: TbPolaroid,
  Polygon: TbPolygon,
  Poo: TbPoo,
  Pool: TbPool,
  Power: TbPower,
  Pray: TbPray,
  PremiumRights: TbPremiumRights,
  Prescription: TbPrescription,
  PresentationAnalytics: TbPresentationAnalytics,
  Presentation: TbPresentation,
  Printer: TbPrinter,
  Prison: TbPrison,
  Prompt: TbPrompt,
  Propeller: TbPropeller,
  Puzzle2: TbPuzzle2,
  Puzzle: TbPuzzle,
  Pyramid: TbPyramid,
  Qrcode: TbQrcode,
  QuestionMark: TbQuestionMark,
  Quote: TbQuote,
  Radar2: TbRadar2,
  Radar: TbRadar,
  Radio: TbRadio,
  Radioactive: TbRadioactive,
  RadiusBottomLeft: TbRadiusBottomLeft,
  RadiusBottomRight: TbRadiusBottomRight,
  RadiusTopLeft: TbRadiusTopLeft,
  RadiusTopRight: TbRadiusTopRight,
  Rainbow: TbRainbow,
  Rating12Plus: TbRating12Plus,
  Rating14Plus: TbRating14Plus,
  Rating16Plus: TbRating16Plus,
  Rating18Plus: TbRating18Plus,
  Rating21Plus: TbRating21Plus,
  Receipt2: TbReceipt2,
  ReceiptRefund: TbReceiptRefund,
  ReceiptTax: TbReceiptTax,
  Receipt: TbReceipt,
  Recharging: TbRecharging,
  RecordMail: TbRecordMail,
  RectangleVertical: TbRectangleVertical,
  Rectangle: TbRectangle,
  Recycle: TbRecycle,
  RefreshAlert: TbRefreshAlert,
  RefreshDot: TbRefreshDot,
  Refresh: TbRefresh,
  Registered: TbRegistered,
  RelationManyToMany: TbRelationManyToMany,
  RelationOneToMany: TbRelationOneToMany,
  RelationOneToOne: TbRelationOneToOne,
  RepeatOnce: TbRepeatOnce,
  Repeat: TbRepeat,
  Replace: TbReplace,
  ReportAnalytics: TbReportAnalytics,
  ReportMedical: TbReportMedical,
  ReportMoney: TbReportMoney,
  ReportSearch: TbReportSearch,
  Report: TbReport,
  Resize: TbResize,
  Ripple: TbRipple,
  RoadSign: TbRoadSign,
  Road: TbRoad,
  Robot: TbRobot,
  Rocket: TbRocket,
  RollerSkating: TbRollerSkating,
  Rollercoaster: TbRollercoaster,
  Rotate2: TbRotate2,
  Rotate360: TbRotate360,
  RotateClockwise2: TbRotateClockwise2,
  RotateClockwise: TbRotateClockwise,
  RotateDot: TbRotateDot,
  RotateRectangle: TbRotateRectangle,
  Rotate: TbRotate,
  Route: TbRoute,
  Router: TbRouter,
  RowInsertBottom: TbRowInsertBottom,
  RowInsertTop: TbRowInsertTop,
  Rss: TbRss,
  Ruler2: TbRuler2,
  Ruler3: TbRuler3,
  RulerMeasure: TbRulerMeasure,
  Ruler: TbRuler,
  Run: TbRun,
  Sailboat: TbSailboat,
  Salt: TbSalt,
  Satellite: TbSatellite,
  Sausage: TbSausage,
  ScaleOutline: TbScaleOutline,
  Scale: TbScale,
  ScanEye: TbScanEye,
  Scan: TbScan,
  Schema: TbSchema,
  School: TbSchool,
  Scissors: TbScissors,
  ScooterElectric: TbScooterElectric,
  Scooter: TbScooter,
  ScreenShare: TbScreenShare,
  Screenshot: TbScreenshot,
  Scribble: TbScribble,
  ScubaMask: TbScubaMask,
  Search: TbSearch,
  SectionSign: TbSectionSign,
  Section: TbSection,
  Seeding: TbSeeding,
  Select: TbSelect,
  Selector: TbSelector,
  Send: TbSend,
  Seo: TbSeo,
  SeparatorHorizontal: TbSeparatorHorizontal,
  SeparatorVertical: TbSeparatorVertical,
  Separator: TbSeparator,
  Server2: TbServer2,
  Server: TbServer,
  Servicemark: TbServicemark,
  SettingsAutomation: TbSettingsAutomation,
  Settings: TbSettings,
  Shadow: TbShadow,
  Shape2: TbShape2,
  Shape3: TbShape3,
  Shape: TbShape,
  Share: TbShare,
  ShieldCheck: TbShieldCheck,
  ShieldCheckered: TbShieldCheckered,
  ShieldChevron: TbShieldChevron,
  ShieldLock: TbShieldLock,
  ShieldX: TbShieldX,
  Shield: TbShield,
  Ship: TbShip,
  ShirtSport: TbShirtSport,
  Shirt: TbShirt,
  Shoe: TbShoe,
  ShoppingCartDiscount: TbShoppingCartDiscount,
  ShoppingCartPlus: TbShoppingCartPlus,
  ShoppingCartX: TbShoppingCartX,
  ShoppingCart: TbShoppingCart,
  Shovel: TbShovel,
  Shredder: TbShredder,
  SignLeft: TbSignLeft,
  SignRight: TbSignRight,
  Signal3g: TbSignal3g,
  Signal4gPlus: TbSignal4gPlus,
  Signal4g: TbSignal4g,
  Signal5g: TbSignal5g,
  Signature: TbSignature,
  Sitemap: TbSitemap,
  Skateboard: TbSkateboard,
  Skull: TbSkull,
  Sleigh: TbSleigh,
  Slice: TbSlice,
  Slideshow: TbSlideshow,
  SmartHome: TbSmartHome,
  SmokingNo: TbSmokingNo,
  Smoking: TbSmoking,
  Snowflake: TbSnowflake,
  Snowman: TbSnowman,
  SoccerField: TbSoccerField,
  Social: TbSocial,
  Sock: TbSock,
  Sofa: TbSofa,
  SortAscending2: TbSortAscending2,
  SortAscendingLetters: TbSortAscendingLetters,
  SortAscendingNumbers: TbSortAscendingNumbers,
  SortAscending: TbSortAscending,
  SortDescending2: TbSortDescending2,
  SortDescendingLetters: TbSortDescendingLetters,
  SortDescendingNumbers: TbSortDescendingNumbers,
  SortDescending: TbSortDescending,
  Sos: TbSos,
  Soup: TbSoup,
  Space: TbSpace,
  SpacingHorizontal: TbSpacingHorizontal,
  SpacingVertical: TbSpacingVertical,
  Spade: TbSpade,
  Speakerphone: TbSpeakerphone,
  Speedboat: TbSpeedboat,
  Spider: TbSpider,
  Spiral: TbSpiral,
  SportBillard: TbSportBillard,
  Spy: TbSpy,
  Square0: TbSquareF0,
  Square1: TbSquareF1,
  Square2: TbSquareF2,
  Square3: TbSquareF3,
  Square4: TbSquareF4,
  Square5: TbSquareF5,
  Square6: TbSquareF6,
  Square7: TbSquareF7,
  Square8: TbSquareF8,
  Square9: TbSquareF9,
  SquareAsterisk: TbSquareAsterisk,
  SquareCheck: TbSquareCheck,
  SquareDot: TbSquareDot,
  SquareForbid2: TbSquareForbid2,
  SquareForbid: TbSquareForbid,
  SquareHalf: TbSquareHalf,
  SquareMinus: TbSquareMinus,
  SquarePlus: TbSquarePlus,
  SquareRoot2: TbSquareRoot2,
  SquareRoot: TbSquareRoot,
  SquareRotatedForbid2: TbSquareRotatedForbid2,
  SquareRotatedForbid: TbSquareRotatedForbid,
  SquareRotated: TbSquareRotated,
  SquareToggleHorizontal: TbSquareToggleHorizontal,
  SquareToggle: TbSquareToggle,
  SquareX: TbSquareX,
  Square: TbSquare,
  SquaresDiagonal: TbSquaresDiagonal,
  SquaresFilled: TbSquaresFilled,
  Stack2: TbStack2,
  Stack3: TbStack3,
  StackPop: TbStackPop,
  StackPush: TbStackPush,
  Stack: TbStack,
  StairsDown: TbStairsDown,
  StairsUp: TbStairsUp,
  Stairs: TbStairs,
  StarHalf: TbStarHalf,
  Star: TbStar,
  Stars: TbStars,
  Steam: TbSteam,
  SteeringWheel: TbSteeringWheel,
  StepInto: TbStepInto,
  StepOut: TbStepOut,
  Stethoscope: TbStethoscope,
  Sticker: TbSticker,
  Storm: TbStorm,
  Strikethrough: TbStrikethrough,
  Submarine: TbSubmarine,
  Subscript: TbSubscript,
  Subtask: TbSubtask,
  Sum: TbSum,
  SunHigh: TbSunHigh,
  SunLow: TbSunLow,
  SunWind: TbSunWind,
  Sun: TbSun,
  Sunglasses: TbSunglasses,
  Sunrise: TbSunrise,
  Sunset2: TbSunset2,
  Sunset: TbSunset,
  Superscript: TbSuperscript,
  Svg: TbSvg,
  Swimming: TbSwimming,
  Switch2: TbSwitch2,
  Switch3: TbSwitch3,
  SwitchHorizontal: TbSwitchHorizontal,
  SwitchVertical: TbSwitchVertical,
  Switch: TbSwitch,
  Sword: TbSword,
  Swords: TbSwords,
  TableAlias: TbTableAlias,
  TableExport: TbTableExport,
  TableImport: TbTableImport,
  TableOptions: TbTableOptions,
  TableShortcut: TbTableShortcut,
  Table: TbTable,
  Tag: TbTag,
  Tags: TbTags,
  Tallymark1: TbTallymark1,
  Tallymark2: TbTallymark2,
  Tallymark3: TbTallymark3,
  Tallymark4: TbTallymark4,
  Tallymarks: TbTallymarks,
  Tank: TbTank,
  Target: TbTarget,
  Telescope: TbTelescope,
  TemperatureCelsius: TbTemperatureCelsius,
  TemperatureFahrenheit: TbTemperatureFahrenheit,
  TemperatureMinus: TbTemperatureMinus,
  TemperaturePlus: TbTemperaturePlus,
  Temperature: TbTemperature,
  Template: TbTemplate,
  Tent: TbTent,
  Terminal2: TbTerminal2,
  Terminal: TbTerminal,
  TestPipe2: TbTestPipe2,
  TestPipe: TbTestPipe,
  TextDecrease: TbTextDecrease,
  TextDirectionLtr: TbTextDirectionLtr,
  TextDirectionRtl: TbTextDirectionRtl,
  TextIncrease: TbTextIncrease,
  TextRecognition: TbTextRecognition,
  TextResize: TbTextResize,
  TextWrapDisabled: TbTextWrapDisabled,
  TextWrap: TbTextWrap,
  Thermometer: TbThermometer,
  ThumbDown: TbThumbDown,
  ThumbUp: TbThumbUp,
  Ticket: TbTicket,
  Tie: TbTie,
  TiltShift: TbTiltShift,
  Timeline: TbTimeline,
  Tir: TbTir,
  ToggleLeft: TbToggleLeft,
  ToggleRight: TbToggleRight,
  ToiletPaper: TbToiletPaper,
  Tool: TbTool,
  ToolsKitchen2: TbToolsKitchen2,
  ToolsKitchen: TbToolsKitchen,
  Tools: TbTools,
  Tornado: TbTornado,
  Tournament: TbTournament,
  Track: TbTrack,
  Tractor: TbTractor,
  Trademark: TbTrademark,
  TrafficCone: TbTrafficCone,
  TrafficLights: TbTrafficLights,
  Train: TbTrain,
  TransferIn: TbTransferIn,
  TransferOut: TbTransferOut,
  TrashX: TbTrashX,
  Trash: TbTrash,
  Tree: TbTree,
  Trees: TbTrees,
  TrendingDown2: TbTrendingDown2,
  TrendingDown3: TbTrendingDown3,
  TrendingDown: TbTrendingDown,
  TrendingUp2: TbTrendingUp2,
  TrendingUp3: TbTrendingUp3,
  TrendingUp: TbTrendingUp,
  TriangleInverted: TbTriangleInverted,
  TriangleSquareCircle: TbTriangleSquareCircle,
  Triangle: TbTriangle,
  Triangles: TbTriangles,
  Trident: TbTrident,
  Trophy: TbTrophy,
  TruckDelivery: TbTruckDelivery,
  TruckLoading: TbTruckLoading,
  TruckReturn: TbTruckReturn,
  Truck: TbTruck,
  Typography: TbTypography,
  Ufo: TbUfo,
  Umbrella: TbUmbrella,
  Underline: TbUnderline,
  Unlink: TbUnlink,
  Upload: TbUpload,
  Urgent: TbUrgent,
  Usb: TbUsb,
  UserCheck: TbUserCheck,
  UserCircle: TbUserCircle,
  UserExclamation: TbUserExclamation,
  UserMinus: TbUserMinus,
  UserPlus: TbUserPlus,
  UserSearch: TbUserSearch,
  UserX: TbUserX,
  User: TbUser,
  Users: TbUsers,
  VaccineBottle: TbVaccineBottle,
  Vaccine: TbVaccine,
  Variable: TbVariable,
  VectorBezier2: TbVectorBezier2,
  VectorBezier: TbVectorBezier,
  VectorTriangle: TbVectorTriangle,
  Vector: TbVector,
  Venus: TbVenus,
  Versions: TbVersions,
  VideoMinus: TbVideoMinus,
  VideoPlus: TbVideoPlus,
  Video: TbVideo,
  View360: TbView360,
  Viewfinder: TbViewfinder,
  ViewportNarrow: TbViewportNarrow,
  ViewportWide: TbViewportWide,
  Vinyl: TbVinyl,
  VirusSearch: TbVirusSearch,
  Virus: TbVirus,
  Vocabulary: TbVocabulary,
  Volume2: TbVolume2,
  Volume3: TbVolume3,
  Volume: TbVolume,
  Walk: TbWalk,
  Wall: TbWall,
  Wallet: TbWallet,
  Wallpaper: TbWallpaper,
  Wand: TbWand,
  WashMachine: TbWashMachine,
  WaveSawTool: TbWaveSawTool,
  WaveSine: TbWaveSine,
  WaveSquare: TbWaveSquare,
  Webhook: TbWebhook,
  Wheelchair: TbWheelchair,
  Wifi0: TbWifi0,
  Wifi1: TbWifi1,
  Wifi2: TbWifi2,
  Wifi: TbWifi,
  Wind: TbWind,
  Windmill: TbWindmill,
  WindowMaximize: TbWindowMaximize,
  WindowMinimize: TbWindowMinimize,
  Window: TbWindow,
  Windsock: TbWindsock,
  WiperWash: TbWiperWash,
  Wiper: TbWiper,
  Woman: TbWoman,
  WorldDownload: TbWorldDownload,
  WorldLatitude: TbWorldLatitude,
  WorldLongitude: TbWorldLongitude,
  WorldUpload: TbWorldUpload,
  World: TbWorld,
  WreckingBall: TbWreckingBall,
  WritingSign: TbWritingSign,
  Writing: TbWriting,
  X: TbX,
  YinYang: TbYinYang,
  Yoga: TbYoga,
  Zeppelin: TbZeppelin,
  ZodiacAquarius: TbZodiacAquarius,
  ZodiacAries: TbZodiacAries,
  ZodiacCancer: TbZodiacCancer,
  ZodiacCapricorn: TbZodiacCapricorn,
  ZodiacGemini: TbZodiacGemini,
  ZodiacLeo: TbZodiacLeo,
  ZodiacLibra: TbZodiacLibra,
  ZodiacPisces: TbZodiacPisces,
  ZodiacSagittarius: TbZodiacSagittarius,
  ZodiacScorpio: TbZodiacScorpio,
  ZodiacTaurus: TbZodiacTaurus,
  ZodiacVirgo: TbZodiacVirgo,
  ZoomCancel: TbZoomCancel,
  ZoomCheck: TbZoomCheck,
  ZoomCode: TbZoomCode,
  ZoomExclamation: TbZoomExclamation,
  ZoomInArea: TbZoomInArea,
  ZoomIn: TbZoomIn,
  ZoomMoney: TbZoomMoney,
  ZoomOutArea: TbZoomOutArea,
  ZoomOut: TbZoomOut,
  ZoomPan: TbZoomPan,
  ZoomQuestion: TbZoomQuestion,
  ZoomReset: TbZoomReset,
  Zzz: TbZzz
}
