name: Lint

on: [push]

jobs:
  typecheck:
    name: Type check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.6.4

      - name: Install dependencies
        run: bun install

      - name: Run type checks
        run: bun typecheck

  eslint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.6.4

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun lint
