name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      JWT_SECRET: testing
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sconet

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.6.4
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bun run playwright install --with-deps
      - name: Run Playwright tests
        run: bun run playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
