name: Typecheck

on: [push]

jobs:
  typecheck:
    name: Type check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.5.1

      - name: Install dependencies
        run: pnpm install

      - name: Run type checks
        run: pnpm typecheck
